### ISSUE TITLE
Unicode Issue (i think)

### ISSUE THREAD

**Issue by rcdosado** [lra/mackup#1020]
Getting this error after runnning `mackup backup`
> Traceback (most recent call last):
>   File "/usr/local/bin/mackup", line 11, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python2.7/dist-packages/mackup/main.py", line 65, in main
>     app_db = ApplicationsDatabase()
>   File "/usr/local/lib/python2.7/dist-packages/mackup/appsdb.py", line 34, in __init__
>     if config.read(config_file):
>   File "/usr/local/lib/python2.7/dist-packages/backports/configparser/__init__.py", line 705, in read
>     self._read(fp, filename)
>   File "/usr/local/lib/python2.7/dist-packages/backports/configparser/__init__.py", line 1109, in _read
>     optname = self.optionxform(optname.rstrip())
> UnicodeEncodeError: 'ascii' codec can't encode character u'\xdc' in position 28: ordinal not in range(128)

my .mackup.cfg contains

> [storage]
> engine = file_system
> path = ~/backup_mackup

i am using ubuntu 16.04, 64 bit
installed mackup, by typing `sudo pip install --upgrade mackup`
python defaults to 2.7 when opened in terminal
any workaround?thanks

**Comment by filiphrenic** [comment]
delete the `/usr/local/Cellar/mackup/0.8.16/libexec/lib/python2.7/site-packages/mackup/applications/ubersicht.cfg` (modify apropriately) because it's the one causing problems

**Comment by ppptok** [comment]
Thanks! Deleting `ubersicht.cfg` did the trick.
