### ISSUE TITLE
Which version of Python is required?

### ISSUE THREAD

**Issue by delahaya** [lra/mackup#1034]
When attempting to run `mackup backup` I receive the following traceback errors...

```python
Traceback (most recent call last):
  File "/usr/local/Cellar/mackup/0.8.16/libexec/bin/mackup", line 9, in <module>
    load_entry_point('mackup==0.8.16', 'console_scripts', 'mackup')()
  File "/usr/local/Cellar/mackup/0.8.16/libexec/lib/python2.7/site-packages/mackup/main.py", line 65, in main
    app_db = ApplicationsDatabase()
  File "/usr/local/Cellar/mackup/0.8.16/libexec/lib/python2.7/site-packages/mackup/appsdb.py", line 34, in __init__
    if config.read(config_file):
  File "/Library/Python/2.7/site-packages/backports/configparser/__init__.py", line 705, in read
    self._read(fp, filename)
  File "/Library/Python/2.7/site-packages/backports/configparser/__init__.py", line 1109, in _read
    optname = self.optionxform(optname.rstrip())
UnicodeEncodeError: 'ascii' codec can't encode character u'\xdc' in position 28: ordinal not in range(128)
```

Which version of python is required to run `mackup`?  I feel like I'm missing something with the installation.  I installed with `brew install` and I installed the `requirements.txt`.

Thank you!!

**Comment by catesandrew** [comment]
```
 130 ❯ mackup backup
Traceback (most recent call last):
  File "/usr/local/Cellar/mackup/0.8.16/libexec/bin/mackup", line 9, in <module>
    load_entry_point('mackup==0.8.16', 'console_scripts', 'mackup')()
  File "/usr/local/Cellar/mackup/0.8.16/libexec/lib/python2.7/site-packages/mackup/main.py", line 65, in main
    app_db = ApplicationsDatabase()
  File "/usr/local/Cellar/mackup/0.8.16/libexec/lib/python2.7/site-packages/mackup/appsdb.py", line 34, in __init__
    if config.read(config_file):
  File "/usr/local/lib/python2.7/site-packages/backports/configparser/__init__.py", line 705, in read
    self._read(fp, filename)
  File "/usr/local/lib/python2.7/site-packages/backports/configparser/__init__.py", line 1035, in _read
    for lineno, line in enumerate(fp, start=1):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 82: ordinal not in range(128)
```

i got the same error and wondering same thing. currently using system python 2.7 on osx and mackup installed through homebrew, v0.8.16

**Comment by catesandrew** [comment]
fixed with comments from [1020](https://github.com/lra/mackup/issues/1020).
