### ISSUE TITLE
Errors with /keybase file system

### ISSUE THREAD

**Issue by andreadellacorte** [lra/mackup#1048]
I am trying to use mackup with Keybase, but I am getting some errors

`Backing up .subversion ...
Traceback (most recent call last):
  File "/usr/local/Cellar/mackup/0.8.16/libexec/bin/mackup", line 9, in <module>
    load_entry_point('mackup==0.8.16', 'console_scripts', 'mackup')()
  File "/usr/local/Cellar/mackup/0.8.16/libexec/lib/python2.7/site-packages/mackup/main.py", line 90, in main
    app.backup()
  File "/usr/local/Cellar/mackup/0.8.16/libexec/lib/python2.7/site-packages/mackup/application.py", line 114, in backup
    utils.copy(home_filepath, mackup_filepath)
  File "/usr/local/Cellar/mackup/0.8.16/libexec/lib/python2.7/site-packages/mackup/utils.py", line 105, in copy
    shutil.copytree(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 208, in copytree
    raise Error, errors
shutil.Error: [('/Users/andrea/.subversion/auth/svn.simple', '/keybase/private/andreadellacorte/Mackup/.subversion/auth/svn.simple', "[Errno 78] Function not implemented: '/keybase/private/andreadellacorte/Mackup/.subversion/auth/svn.simple'"), ('/Users/andrea/.subversion/auth/svn.ssl.client-passphrase', '/keybase/private/andreadellacorte/Mackup/.subversion/auth/svn.ssl.client-passphrase', "[Errno 78] Function not implemented: '/keybase/private/andreadellacorte/Mackup/.subversion/auth/svn.ssl.client-passphrase'"), ('/Users/andrea/.subversion/auth/svn.ssl.server', '/keybase/private/andreadellacorte/Mackup/.subversion/auth/svn.ssl.server', "[Errno 78] Function not implemented: '/keybase/private/andreadellacorte/Mackup/.subversion/auth/svn.ssl.server'"), ('/Users/andrea/.subversion/auth/svn.username', '/keybase/private/andreadellacorte/Mackup/.subversion/auth/svn.username', "[Errno 78] Function not implemented: '/keybase/private/andreadellacorte/Mackup/.subversion/auth/svn.username'"), ('/Users/andrea/.subversion/auth', '/keybase/private/andreadellacorte/Mackup/.subversion/auth', "[Errno 78] Function not implemented: '/keybase/private/andreadellacorte/Mackup/.subversion/auth'"), ('/Users/andrea/.subversion', '/keybase/private/andreadellacorte/Mackup/.subversion', "[Errno 78] Function not implemented: '/keybase/private/andreadellacorte/Mackup/.subversion'")]`

**Comment by headless1** [comment]
Keybase support would be awesome for this!

**Comment by Christilut** [comment]
Keybase support would be awesome for this!
