### ISSUE TITLE
Error backing up emacs

### ISSUE THREAD

**Issue by heyarne** [lra/mackup#1095]
Hi,
I'm on macos 10.13, emacs 25.3.1 and I'm using the spacemacs configuration framework (current commit 4bb4cb46).

I tried `mackup backup` but it gave me the following error:

```
Backing up .emacs.d ... Traceback (most recent call last): File "/usr/local/Cellar/mackup/0.8.16/libexec/bin/mackup", line 9, in <module> load_entry_point('mackup==0.8.16', 'console_scripts', 'mackup')() File "/usr/local/Cellar/mackup/0.8.16/libexec/lib/python2.7/site-packages/mackup/main.py", line 90, in main app.backup() File "/usr/local/Cellar/mackup/0.8.16/libexec/lib/python2.7/site-packages/mackup/application.py", line 114, in backup utils.copy(home_filepath, mackup_filepath) File "/usr/local/Cellar/mackup/0.8.16/libexec/lib/python2.7/site-packages/mackup/utils.py", line 105, in copy shutil.copytree(src, dst) File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 208, in copytree raise Error, errors shutil.Error: [('/Users/heyarne/.emacs.d/elpa/gnupg/S.gpg-agent.extra', '/Users/heyarne/.config/Mackup/.emacs.d/elpa/gnupg/S.gpg-agent.extra', "[Errno 102] Operation not supported on socket: '/Users/heyarne/.emacs.d/elpa/gnupg/S.gpg-agent.extra'"), ('/Users/heyarne/.emacs.d/elpa/gnupg/S.gpg-agent.ssh', '/Users/heyarne/.config/Mackup/.emacs.d/elpa/gnupg/S.gpg-agent.ssh', "[Errno 102] Operation not supported on socket: '/Users/heyarne/.emacs.d/elpa/gnupg/S.gpg-agent.ssh'"), ('/Users/heyarne/.emacs.d/elpa/gnupg/S.gpg-agent', '/Users/heyarne/.config/Mackup/.emacs.d/elpa/gnupg/S.gpg-agent', "[Errno 102] Operation not supported on socket: '/Users/heyarne/.emacs.d/elpa/gnupg/S.gpg-agent'"), ('/Users/heyarne/.emacs.d/elpa/gnupg/S.gpg-agent.browser', '/Users/heyarne/.config/Mackup/.emacs.d/elpa/gnupg/S.gpg-agent.browser', "[Errno 102] Operation not supported on socket: '/Users/heyarne/.emacs.d/elpa/gnupg/S.gpg-agent.browser'")]
```

What exactly is the issue with the gpg socket? Any idea how to fix it? Thanks in advance

**Comment by WilsonChiang** [comment]
Same thing here :(

**Comment by JasonMFry** [comment]
Same here

```
Backing up .emacs.d ...
A folder named /Users/j/Library/Mobile Documents/com~apple~CloudDocs/Mackup/.emacs.d already exists in the backup.
Are you sure that you want to replace it ? <Yes|No>y
Traceback (most recent call last):
  File "/usr/local/bin/mackup", line 33, in <module>
    sys.exit(load_entry_point('mackup==0.8.29', 'console_scripts', 'mackup')())
  File "/usr/local/Cellar/mackup/0.8.29_1/libexec/lib/python3.9/site-packages/mackup/main.py", line 93, in main
    app.backup()
  File "/usr/local/Cellar/mackup/0.8.29_1/libexec/lib/python3.9/site-packages/mackup/application.py", line 110, in backup
    utils.copy(home_filepath, mackup_filepath)
  File "/usr/local/Cellar/mackup/0.8.29_1/libexec/lib/python3.9/site-packages/mackup/utils.py", line 105, in copy
    shutil.copytree(src, dst)
  File "/usr/local/Cellar/python@3.9/3.9.1_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/usr/local/Cellar/python@3.9/3.9.1_2/Frameworks/Python.framework/Versions/3.9/lib/python3.9/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/j/.emacs.d/.local/elpa/gpg/S.gpg-agent.extra', '/Users/j/Library/Mobile Documents/com~apple~CloudDocs/Mackup/.emacs.d/.local/elpa/gpg/S.gpg-agent.extra', "[Errno 102] Operation not supported on socket: '/Users/j/.emacs.d/.local/elpa/gpg/S.gpg-agent.extra'"), ('/Users/j/.emacs.d/.local/elpa/gpg/S.gpg-agent.ssh', '/Users/j/Library/Mobile Documents/com~apple~CloudDocs/Mackup/.emacs.d/.local/elpa/gpg/S.gpg-agent.ssh', "[Errno 102] Operation not supported on socket: '/Users/j/.emacs.d/.local/elpa/gpg/S.gpg-agent.ssh'"), ('/Users/j/.emacs.d/.local/elpa/gpg/S.gpg-agent', '/Users/j/Library/Mobile Documents/com~apple~CloudDocs/Mackup/.emacs.d/.local/elpa/gpg/S.gpg-agent', "[Errno 102] Operation not supported on socket: '/Users/j/.emacs.d/.local/elpa/gpg/S.gpg-agent'"), ('/Users/j/.emacs.d/.local/elpa/gpg/S.gpg-agent.browser', '/Users/j/Library/Mobile Documents/com~apple~CloudDocs/Mackup/.emacs.d/.local/elpa/gpg/S.gpg-agent.browser', "[Errno 102] Operation not supported on socket: '/Users/j/.emacs.d/.local/elpa/gpg/S.gpg-agent.browser'")]
```

**Comment by lra** [comment]
Yes, mackup does not like file sockets. If your application generate some, I suggest disabling it.
I could remove support for emacs entirely, but it would impact all emacs users, even those who don't use those plugins.
If this is preferable, LMK.
