### ISSUE TITLE
UnicodeDecodeError when backup

### ISSUE THREAD

**Issue by geekspeng** [lra/mackup#1178]
$ mackup backup
Traceback (most recent call last):
  File "/usr/local/Cellar/mackup/0.8.18/libexec/bin/mackup", line 9, in <module>
    load_entry_point('mackup==0.8.18', 'console_scripts', 'mackup')()
  File "/usr/local/Cellar/mackup/0.8.18/libexec/lib/python2.7/site-packages/mackup/main.py", line 65, in main
    app_db = ApplicationsDatabase()
  File "/usr/local/Cellar/mackup/0.8.18/libexec/lib/python2.7/site-packages/mackup/appsdb.py", line 34, in __init__
    if config.read(config_file):
  File "/Users/geekspeng/Library/Python/2.7/lib/python/site-packages/backports/configparser/__init__.py", line 705, in read
    self._read(fp, filename)
  File "/Users/geekspeng/Library/Python/2.7/lib/python/site-packages/backports/configparser/__init__.py", line 1109, in _read
    optname = self.optionxform(optname.rstrip())
UnicodeEncodeError: 'ascii' codec can't encode character u'\xdc' in position 28: ordinal not in range(128)

**Comment by gustavobittencourt** [comment]
I am having this same error.

**Comment by gudzenkov** [comment]
the same error, both with brew or pip installations

**Comment by tildebyte** [comment]
You've pip-installed `configparser` at some point (or something has pulled it in as a dependency). pip-uninstall it and try again (worked for me).

**Comment by AlanOSLLiu** [comment]
same error
