### ISSUE TITLE
Electrum doesn't backup bitcoin wallets

### ISSUE THREAD

**Issue by spuder** [lra/mackup#1242]
Mackup will backup the `config` file, but will not backup the `wallets` directory. 

Before I open a merge request, I'd like to start a discussion to hear any arguments why the wallets _shouldn't_ be backed up as well. The wallets are infinitely more valuable and I believe should also be backed up. 

@rbartoli Any reason why wallets shouldn't be included?

**Comment by lra** [comment]
Same issue as ssh private keys, the issue is that mackup does not know where the user is syncing its files. It could be on a public cloud (like dropbox) and password-less, which could be an issue for some users. Other users might use a very secure backup place and might prefer to backup everything with mackup.

As it's a user's preference, I kind of think it's up to the user to customize his setup, and keep defaults safe.

**Comment by spuder** [comment]
Well that is quite alarming. Wouldn't the safest option be the one that has the least likelihood of omitting data? 

I've assumed for years that mackup was backing up everything (multiple mac restores has proved that to be true). I've read the readme and the docs directory twice, and I'm not able to see a clear example of how one would configure mackup to get the private keys (ssh) and bitcoin wallets? Once I figure it out I'll open a merge request so others don't fall into the same assumption that I had. 


```
touch ~/.mackup.cfg
```

~/.mackup.cfg
```
[configuration_files]
~/.electrum/wallets/
```

Yet it would appear mackup is very particular about the contents of the ~/.mackup.cfg file
```
Traceback (most recent call last):
  File "/usr/local/Cellar/mackup/0.8.18/libexec/bin/mackup", line 9, in <module>
    load_entry_point('mackup==0.8.18', 'console_scripts', 'mackup')()
  File "/usr/local/Cellar/mackup/0.8.18/libexec/lib/python2.7/site-packages/mackup/main.py", line 65, in main
    app_db = ApplicationsDatabase()
  File "/usr/local/Cellar/mackup/0.8.18/libexec/lib/python2.7/site-packages/mackup/appsdb.py", line 44, in __init__
    app_pretty_name = config.get('application', 'name')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'application'
```

**Comment by lra** [comment]
It was the case before (default to backup everything), but some users asked me to change the behavior and exclude private keys.

Not sure how to please everyone here.

**Comment by lra** [comment]
```
$ cat ~/.mackup/ssh.cfg 
[application]
name = SSH

[configuration_files]
.ssh
```

**Comment by jamiew** [comment]
Old ticket, but maybe we have something like a "post-install hook" that adds warnings for cases like this? I ran into this as well, and it was easy to solve with a `~/.mackup/electrum.cfg`, but I had to be paying attention

**Comment by lra** [comment]
Yeah, I kind of think we should keep the behavior simple (works the same way for every application) and if people don't trust their backup, they can customize their config or not backup anything.

What do you think of coming back to a "backup everything" default? How would a warning message look like? (on the website, not on the CLI)?
