### ISSUE TITLE
Mojave, new workstation

### ISSUE THREAD

**Issue by pastephens** [lra/mackup#1253]
Hi, I'm on a new workstation with Dropbox installed.  I installed mackup with pip and ran 'mackup restore' and got this:

Traceback (most recent call last):
  File "/usr/local/bin/mackup", line 9, in <module>
    load_entry_point('mackup==0.8.20', 'console_scripts', 'mackup')()
  File "/Library/Python/2.7/site-packages/mackup/main.py", line 65, in main
    app_db = ApplicationsDatabase()
  File "/Library/Python/2.7/site-packages/mackup/appsdb.py", line 63, in __init__
    .format(xdg_config_home))
ValueError: $XDG_CONFIG_HOME: /Users/stephens/.config does not exist

**Comment by cheeaun** [comment]
Also getting the same thing:

```
$ mackup restore
Traceback (most recent call last):
  File "/usr/local/bin/mackup", line 11, in <module>
    load_entry_point('mackup==0.8.20', 'console_scripts', 'mackup')()
  File "/usr/local/Cellar/mackup/0.8.20/libexec/lib/python3.7/site-packages/mackup/main.py", line 65, in main
    app_db = ApplicationsDatabase()
  File "/usr/local/Cellar/mackup/0.8.20/libexec/lib/python3.7/site-packages/mackup/appsdb.py", line 63, in __init__
    .format(xdg_config_home))
ValueError: $XDG_CONFIG_HOME: /Users/cheeaun/.config does not exist
```

**Comment by tpeters67** [comment]
Same here just happened in the last update. Have also just updated to Mojave.
`$ mackup list
Traceback (most recent call last):
  File "/usr/local/bin/mackup", line 11, in <module>
    load_entry_point('mackup==0.8.20', 'console_scripts', 'mackup')()
  File "/usr/local/Cellar/mackup/0.8.20/libexec/lib/python3.7/site-packages/mackup/main.py", line 65, in main
    app_db = ApplicationsDatabase()
  File "/usr/local/Cellar/mackup/0.8.20/libexec/lib/python3.7/site-packages/mackup/appsdb.py", line 63, in __init__
    .format(xdg_config_home))
ValueError: $XDG_CONFIG_HOME: /Users/tpeters/.config does not exist`

**Comment by calumbrodie** [comment]
Also had this issue, a very dirty workaround is to set the missing variable before restoring

e.g
`export XDG_CONFIG_HOME=/Users/{yourusername_goes_here}/`

**Comment by calumbrodie** [comment]
Possibly introduced here?: https://github.com/lra/mackup/pull/1199

**Comment by tanpengsccd** [comment]
```
mackup backup
Traceback (most recent call last):
  File "/usr/local/bin/mackup", line 11, in <module>
    load_entry_point('mackup==0.8.20', 'console_scripts', 'mackup')()
  File "/usr/local/Cellar/mackup/0.8.20/libexec/lib/python3.7/site-packages/mackup/main.py", line 65, in main
    app_db = ApplicationsDatabase()
  File "/usr/local/Cellar/mackup/0.8.20/libexec/lib/python3.7/site-packages/mackup/appsdb.py", line 63, in __init__
    .format(xdg_config_home))
ValueError: $XDG_CONFIG_HOME: /Users/leo/.config does not exist
```
me too!

**Comment by tanpengsccd** [comment]
Fix with install history version < 0.8.20

```
sudo pip install 'mackup<0.8.20'
```
Hope it work!

**Comment by PaulWaldo** [comment]
I still get the problem on a fresh installation via brew
```
Pauls-MacBook:~ paul$ brew info mackup
mackup: stable 0.8.21 (bottled), HEAD
Keep your Mac's application settings in sync
https://github.com/lra/mackup
/usr/local/Cellar/mackup/0.8.21 (1,012 files, 7.0MB) *
  Poured from bottle on 2019-01-15 at 14:41:19
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/mackup.rb
==> Dependencies
Required: python ✔
==> Options
--HEAD
	Install HEAD version
```
```
Pauls-MacBook:~ paul$ mackup list
Traceback (most recent call last):
  File "/usr/local/bin/mackup", line 11, in <module>
    load_entry_point('mackup==0.8.21', 'console_scripts', 'mackup')()
  File "/usr/local/Cellar/mackup/0.8.21/libexec/lib/python3.7/site-packages/mackup/main.py", line 65, in main
    app_db = ApplicationsDatabase()
  File "/usr/local/Cellar/mackup/0.8.21/libexec/lib/python3.7/site-packages/mackup/appsdb.py", line 63, in __init__
    .format(xdg_config_home))
ValueError: $XDG_CONFIG_HOME: /Users/paul/.config does not exist
```

**Comment by lra** [comment]
I see now, it seems you all define an `XDG_CONFIG_HOME` env var that points to a folder that you did not create.

3 solutions here:
- Mackup can ignore the fact that you specify a non existent folder and not sync anything that's supposed to exist in this folder, silently
- Same as the 1st one, by also display a friendly warning saying that you have specified a folder that do not exists
- Fail fast, displaying a friendlier error message.

**Comment by PaulWaldo** [comment]
No, this variable is not defined:
```
Pauls-MacBook:combiner paul$ env|grep XDG_CONFIG_HOME
Pauls-MacBook:combiner paul$ 
```
