### ISSUE TITLE
Fatal error when backing up Library/PDF Services

### ISSUE THREAD

**Issue by aaronhnatiw** [lra/mackup#1279]
I get the following error that kills the program when running `mackup backup`:

> Backing up Library/PDF Services ...
Traceback (most recent call last):
  File "/usr/local/bin/mackup", line 11, in <module>
    load_entry_point('mackup==0.8.20', 'console_scripts', 'mackup')()
  File "/usr/local/Cellar/mackup/0.8.20/libexec/lib/python3.7/site-packages/mackup/main.py", line 90, in main
    app.backup()
  File "/usr/local/Cellar/mackup/0.8.20/libexec/lib/python3.7/site-packages/mackup/application.py", line 114, in backup
    utils.copy(home_filepath, mackup_filepath)
  File "/usr/local/Cellar/mackup/0.8.20/libexec/lib/python3.7/site-packages/mackup/utils.py", line 102, in copy
    shutil.copytree(src, dst)
  File "/usr/local/Cellar/mackup/0.8.20/libexec/lib/python3.7/shutil.py", line 365, in copytree
    raise Error(errors)
shutil.Error: [('/Users/me/Library/PDF Services/Mail PDF with Postbox', '/Users/me/Google Drive/Mackup/Library/PDF Services/Mail PDF with Postbox', "[Errno 2] No such file or directory: '/Users/me/Library/PDF Services/Mail PDF with Postbox'")]

**Comment by lubocheng** [comment]
I meet the same error, it seems that mackup can't backup config in a folder ??
`
Traceback (most recent call last):
  File "/usr/local/bin/mackup", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/mackup/main.py", line 121, in main
    app.restore()
  File "/usr/local/lib/python3.6/dist-packages/mackup/application.py", line 189, in restore
    utils.link(mackup_filepath, home_filepath)
  File "/usr/local/lib/python3.6/dist-packages/mackup/utils.py", line 142, in link
    os.symlink(target, link_to)
FileNotFoundError: [Errno 2] No such file or directory: '/home/lbc/dotfiles_with_mackup/Mackup/.IntelliJIdea2018.3/config/' -> '/home/lbc/.IntelliJIdea2018.3/config/
`

**Comment by lubocheng** [comment]
@aaronhnatiw 
I finally find out that, when you config some config in path, "/' is not allowed to show in the end of line,
for example,:
```python
[application]  
name = IntelliJ IDEA  
[configuration_files]                                               
IntelliJIdea2018.3/config/
```
above is wrong, it will meet runtime error, below is the right format:
```python
[application]  
name = IntelliJ IDEA  
[configuration_files]                                               
IntelliJIdea2018.3/config
```

**Comment by lra** [comment]
Thanks for figuring this out.
