### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by makabde** [lra/mackup#1284]
Hi,
On a fresh Mojave install, I am getting the following error.
Mackup was installed using Homebrew.

````
Traceback (most recent call last):
  File "/usr/local/bin/mackup", line 11, in <module>
    load_entry_point('mackup==0.8.21', 'console_scripts', 'mackup')()
  File "/usr/local/Cellar/mackup/0.8.21/libexec/lib/python3.7/site-packages/mackup/main.py", line 64, in main
    mckp = Mackup()
  File "/usr/local/Cellar/mackup/0.8.21/libexec/lib/python3.7/site-packages/mackup/mackup.py", line 24, in __init__
    self._config = config.Config()
  File "/usr/local/Cellar/mackup/0.8.21/libexec/lib/python3.7/site-packages/mackup/config.py", line 42, in __init__
    self._parser = self._setup_parser(filename)
  File "/usr/local/Cellar/mackup/0.8.21/libexec/lib/python3.7/site-packages/mackup/config.py", line 148, in _setup_parser
    parser.read(os.path.join(os.path.join(os.environ['HOME'], filename)))
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/configparser.py", line 696, in read
    self._read(fp, filename)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/configparser.py", line 1014, in _read
    for lineno, line in enumerate(fp, start=1):
  File "/usr/local/Cellar/mackup/0.8.21/libexec/bin/../lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe0 in position 24: invalid continuation byte
````

**Comment by lacymorrow** [comment]
yep. 

╰─± mackup backup

Mackup needs a directory to store your configuration files
Do you want to create it now? </Users/tmorrow/Dropbox/Mackup> <Yes|No>Yes
Backing up .aws ...
Traceback (most recent call last):
  File "/usr/local/bin/mackup", line 11, in <module>
    load_entry_point('mackup==0.8.21', 'console_scripts', 'mackup')()
  File "/usr/local/Cellar/mackup/0.8.21/libexec/lib/python3.7/site-packages/mackup/main.py", line 90, in main
    app.backup()
  File "/usr/local/Cellar/mackup/0.8.21/libexec/lib/python3.7/site-packages/mackup/application.py", line 116, in backup
    utils.delete(home_filepath)
  File "/usr/local/Cellar/mackup/0.8.21/libexec/lib/python3.7/site-packages/mackup/utils.py", line 65, in delete
    shutil.rmtree(filepath)
  File "/usr/local/Cellar/mackup/0.8.21/libexec/lib/python3.7/shutil.py", line 491, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/local/Cellar/mackup/0.8.21/libexec/lib/python3.7/shutil.py", line 449, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/local/Cellar/mackup/0.8.21/libexec/lib/python3.7/shutil.py", line 447, in _rmtree_safe_fd
    os.unlink(entry.name, dir_fd=topfd)
PermissionError: [Errno 13] Permission denied: 'credentials'
╭─tmorrow at C02VK0KXHV2J in ~/Projects/twilio-docs on master✔
╰─± sudo mackup backup

Password:
Error: Running Mackup as a superuser is useless and dangerous. Don't do it!

**Comment by TheJayWright** [comment]
Likewise.

**Comment by lra** [comment]
The 2 errors seem to be unrelated. I suggest opening different issue.

@makabde what's your `$HOME`? Is there unicode in it?
@lacymorrow Looks like mackup tries to move some `credentials` files but it can't, due to permission errors.

**Comment by ejfox** [comment]
I think I am encountering a similar issue

```
/Users/ejf/Desktop/2018/vj [ejf@mb417] [9:52]
> mackup backup
Backing up Library/Preferences/com.apple.symbolichotkeys.plist ...
A file named /Users/ejf/Dropbox/Mackup/Library/Preferences/com.apple.symbolichotkeys.plist already exists in the backup.
Are you sure that you want to replace it ? <Yes|No>yes
Backing up Library/Quicklook ...
A folder named /Users/ejf/Dropbox/Mackup/Library/Quicklook already exists in the backup.
Are you sure that you want to replace it ? <Yes|No>yes
Traceback (most recent call last):
  File "/usr/local/bin/mackup", line 11, in <module>
    load_entry_point('mackup==0.8.21', 'console_scripts', 'mackup')()
  File "/usr/local/Cellar/mackup/0.8.21/libexec/lib/python3.7/site-packages/mackup/main.py", line 90, in main
    app.backup()
  File "/usr/local/Cellar/mackup/0.8.21/libexec/lib/python3.7/site-packages/mackup/application.py", line 107, in backup
    utils.copy(home_filepath, mackup_filepath)
  File "/usr/local/Cellar/mackup/0.8.21/libexec/lib/python3.7/site-packages/mackup/utils.py", line 102, in copy
    shutil.copytree(src, dst)
  File "/usr/local/Cellar/mackup/0.8.21/libexec/lib/python3.7/shutil.py", line 365, in copytree
    raise Error(errors)
shutil.Error: [('/Users/ejf/Library/Quicklook/qlImageSize.qlgenerator', '/Users/ejf/Dropbox/Mackup/Library/Quicklook/qlImageSize.qlgenerator', "[Errno 13] Permission denied: '/Users/ejf/Library/Quicklook/qlImageSize.qlgenerator'")]

/Users/ejf/Desktop/2018/vj [ejf@mb417] [9:53]
> ll /Users/ejf/Dropbox/Mackup/Library/Quicklook
total 0
drwxr-xr-x@ 3 ejf  staff  96 Oct  5  2016 QLColorCode.qlgenerator
drwxr-xr-x@ 3 ejf  staff  96 Nov 27  2015 QLMarkdown.qlgenerator
drwxr-xr-x@ 3 ejf  staff  96 Oct 11  2016 QLStephen.qlgenerator
drwxr-xr-x@ 3 ejf  staff  96 Feb  2  2013 QuickLookCSV.qlgenerator
drwxr-xr-x@ 3 ejf  staff  96 Oct 30  2013 QuickLookJSON.qlgenerator
drwxr-xr-x@ 3 ejf  staff  96 Oct 21  2014 WebP.qlgenerator
```
