### ISSUE TITLE
Adobe Illustrator Error

### ISSUE THREAD

**Issue by wschlotter** [lra/mackup#1324]
When running it errors out at Adobe Illustrator. If I bypass Illustrator it works fine.

```
Traceback (most recent call last):
  File "/usr/local/bin/mackup", line 11, in <module>
    load_entry_point('mackup==0.8.22', 'console_scripts', 'mackup')()
  File "/usr/local/Cellar/mackup/0.8.22/libexec/lib/python3.7/site-packages/mackup/main.py", line 90, in main
    app.backup()
  File "/usr/local/Cellar/mackup/0.8.22/libexec/lib/python3.7/site-packages/mackup/application.py", line 114, in backup
    utils.copy(home_filepath, mackup_filepath)
  File "/usr/local/Cellar/mackup/0.8.22/libexec/lib/python3.7/site-packages/mackup/utils.py", line 102, in copy
    shutil.copytree(src, dst)
  File "/usr/local/Cellar/mackup/0.8.22/libexec/lib/python3.7/shutil.py", line 365, in copytree
    raise Error(errors)
shutil.Error: [('/Users/williamschlotter/Library/Preferences/Adobe Illustrator 23 Settings/en_US/Tools/Tools Panel Presets', '/Users/williamschlotter/odrive/Personal/Mackup/Library/Preferences/Adobe Illustrator 23 Settings/en_US/Tools/Tools Panel Presets', "[Errno 2] No such file or directory: '/Users/williamschlotter/Library/Preferences/Adobe Illustrator 23 Settings/en_US/Tools/Tools Panel Presets'"), ('/Users/williamschlotter/Library/Preferences/Adobe Illustrator 23 Settings/en_US/Last Used Artboard Export Settings', '/Users/williamschlotter/odrive/Personal/Mackup/Library/Preferences/Adobe Illustrator 23 Settings/en_US/Last Used Artboard Export Settings', "[Errno 2] No such file or directory: '/Users/williamschlotter/Library/Preferences/Adobe Illustrator 23 Settings/en_US/Last Used Artboard Export Settings'")]
```

**Comment by everdrone** [comment]
Same but with the Workspaces directory

```
Backing up Library/Preferences/Adobe Illustrator 23 Settings/en_US/Tools/Tools Panel Presets ...
Backing up Library/Preferences/Adobe Illustrator 23 Settings/en_US/Workspaces/ ...
Traceback (most recent call last):
  File "/usr/local/bin/mackup", line 11, in <module>
    load_entry_point('mackup==0.8.22', 'console_scripts', 'mackup')()
  File "/usr/local/Cellar/mackup/0.8.22/libexec/lib/python3.7/site-packages/mackup/main.py", line 90, in main
    app.backup()
  File "/usr/local/Cellar/mackup/0.8.22/libexec/lib/python3.7/site-packages/mackup/application.py", line 118, in backup
    utils.link(mackup_filepath, home_filepath)
  File "/usr/local/Cellar/mackup/0.8.22/libexec/lib/python3.7/site-packages/mackup/utils.py", line 142, in link
    os.symlink(target, link_to)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/everdrone/Library/Mobile Documents/com~apple~CloudDocs/Mackup/Library/Preferences/Adobe Illustrator 23 Settings/en_US/Workspaces/' -> '/Users/everdrone/Library/Preferences/Adobe Illustrator 23 Settings/en_US/Workspaces/'
```

**Comment by sjclark** [comment]
Likewise
```
Backing up Library/Application Support/Adobe/Adobe Illustrator 23/en_US/Swatches/ ...
Traceback (most recent call last):
  File "/usr/local/bin/mackup", line 11, in <module>
    load_entry_point('mackup==0.8.22', 'console_scripts', 'mackup')()
  File "/usr/local/Cellar/mackup/0.8.22/libexec/lib/python3.7/site-packages/mackup/main.py", line 90, in main
    app.backup()
  File "/usr/local/Cellar/mackup/0.8.22/libexec/lib/python3.7/site-packages/mackup/application.py", line 118, in backup
    utils.link(mackup_filepath, home_filepath)
  File "/usr/local/Cellar/mackup/0.8.22/libexec/lib/python3.7/site-packages/mackup/utils.py", line 142, in link
    os.symlink(target, link_to)
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sam/Dropbox/Mackup/Library/Application Support/Adobe/Adobe Illustrator 23/en_US/Swatches/' -> '/Users/sam/Library/Application Support/Adobe/Adobe Illustrator 23/en_US/Swatches/'
```

**Comment by mrymtsk** [comment]
This problem is fixed by #1296 & #1298, although they are not included in the release yet. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by metalmini** [comment]
When will this be released?

**Comment by lra** [comment]
Just released https://github.com/lra/mackup/releases/tag/0.8.23

**Comment by metalmini** [comment]
This can be closed
