### ISSUE TITLE
iina backup is not working

### ISSUE THREAD

**Issue by Dj3ross** [lra/mackup#1345]
Hi,
I tried using mackup by explicitely listing apps I want to sync.
I did a dry-run to test everything before actually syncing, and whenever I add "iina", I get the same error I would get if the cfg file didn't exist :

`Traceback (most recent call last):
  File "/usr/local/bin/mackup", line 11, in <module>
    load_entry_point('mackup==0.8.22', 'console_scripts', 'mackup')()
  File "/usr/local/Cellar/mackup/0.8.22/libexec/lib/python3.7/site-packages/mackup/main.py", line 86, in main
    app_db.get_files(app_name),
  File "/usr/local/Cellar/mackup/0.8.22/libexec/lib/python3.7/site-packages/mackup/appsdb.py", line 142, in get_files
    return self.apps[name]['configuration_files']
KeyError: 'iina'`

Am I the only one having issue here ?
Can anyone try it please ?

**Comment by mrymtsk** [comment]
I guess you installed the latest version from Homebrew? Unfortunately, support for IINA is not included in the release yet. You can try installing the HEAD version from Homebrew if you need it: `brew install mackup --HEAD`

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lra** [comment]
Just released https://github.com/lra/mackup/releases/tag/0.8.23
