### ISSUE TITLE
Error unsupported absolute path for Tunnelblick

### ISSUE THREAD

**Issue by madsem** [lra/mackup#1409]
I have a custom config for Tunnelblick, in which I wanted to 'mackup' my VPN config file(s).
But whenever I add this, mackup throws an error:
```shell
➜ mackup list
Traceback (most recent call last):
  File "/usr/local/bin/mackup", line 11, in <module>
    load_entry_point('mackup==0.8.24', 'console_scripts', 'mackup')()
  File "/usr/local/Cellar/mackup/0.8.24/libexec/lib/python3.7/site-packages/mackup/main.py", line 65, in main
    app_db = ApplicationsDatabase()
  File "/usr/local/Cellar/mackup/0.8.24/libexec/lib/python3.7/site-packages/mackup/appsdb.py", line 53, in __init__
    .format(path))
ValueError: Unsupported absolute path: /Library/Application Support/Tunnelblick/Shared
```

When I remove `/Library/Application Support/Tunnelblick/Shared` it works again.

**Comment by lra** [comment]
Try without the leading `/`

**Comment by nbcomplete** [comment]
> Try without the leading `/`

Then it won't work, because Tunnelblick actually uses the root Library folder for VPN profiles, not the folder in the home directory.

I've just discovered the same issue, also with Tunnelblick, so before I stumbled upon this issue I checked the code:

Absolute paths are rejected explictly here: https://github.com/lra/mackup/blob/master/mackup/appsdb.py#L51
because they are joined with the home directory here: https://github.com/lra/mackup/blob/master/mackup/application.py#L44

Was this an intentional design decision? If so, why? I think backing up configs should not be limited to paths under the user's home directory.

**Comment by lra** [comment]
> Was this an intentional design decision? If so, why?

Yes, because the purpose of Mackup is to sync user's files, and no user file is supposed to live outside of the home folder in a multi user system.

Syncing `/` would lead to a lot of breaking things and we already have too much things breaking by just supporting `~`.

Frankly, I don't see any good for any app to store any user setting out of `~`, Tunnelblick should not do this.

**Comment by nbcomplete** [comment]
Good point, but
>Syncing / would lead to a lot of breaking things

You know it would be people intentionally backing up paths that aren't under their home dir, right? It's not like Mackup would interfere with random stuff on people's computers. Still though, I think I could solve this with symlinks, if I still desired to do so.

 I just found that I had installed the VPN profiles as shared, so Tunnelblick was saving them under the global Library directory rather than the the user-local one. But when I tried to make the profiles user-local, Tunnelblick choked due to the symlinked local profile directory (the one that is backed up with the default config). I guess I understand what you mean by breaking stuff now.

Maybe it would be an option to add a second backup strategy to Mackup where it makes copies rather than symlinks?

**Comment by lra** [comment]
> Maybe it would be an option to add a second backup strategy to Mackup where it makes copies rather than symlinks?

This is definitely planned

**Comment by owpac** [comment]
Hello !

I've just found this thread and I was wondering if the option to add a second backup strategy to Mackup where it makes copies rather than symlinks is still something in the roadmap.

In my particular use case (I'm on Mac), I wanted to add some configuration in my Firefox (basically removing some default shortcuts and added new ones). Long story short, it appears that I needed to create 2 files in `/Applications/Firefox.app/Contents/Ressources` and I would love to manage & save those configuration files with Mackup with copies:

```
[application]
name = Firefox conf

[mode]
type = cp

[configuration_files]
/Applications/Firefox.app/Contents/Resources/config.js
/Applications/Firefox.app/Contents/Resources/defaults/pref/config-prefs.js
```
