### ISSUE TITLE
Assertion after running home-brew update

### ISSUE THREAD

**Issue by brbergami** [lra/mackup#1413]
This is on macOS 10.14.6, Mackup 0.8.25.
Storage is pointing to iCloud.
I think at some point home-brew updated python and that triggered the issue.

``` mackup backup
Traceback (most recent call last):
  File "/usr/local/bin/mackup", line 11, in <module>
    load_entry_point('mackup==0.8.25', 'console_scripts', 'mackup')()
  File "/usr/local/Cellar/mackup/0.8.25/libexec/lib/python3.7/site-packages/mackup/main.py", line 89, in main
    verbose)
  File "/usr/local/Cellar/mackup/0.8.25/libexec/lib/python3.7/site-packages/mackup/application.py", line 26, in __init__
    assert isinstance(files, set)
AssertionError```

**Comment by brbergami** [comment]
Also, the uninstall command triggers the same bug.
Tried running brew in repair mode and no fixes are made, so seems it's not a dependency error.

**Comment by lra** [comment]
This has been fixed in https://github.com/lra/mackup/pull/1412
Update Mackup please.

**Comment by sebastiaanluca** [comment]
I'm on 0.8.33, Monterey, M1 Mac Mini

```
Traceback (most recent call last):
  File "/usr/local/bin/mackup", line 33, in <module>
    sys.exit(load_entry_point('mackup==0.8.33', 'console_scripts', 'mackup')())
  File "/usr/local/Cellar/mackup/0.8.33/libexec/lib/python3.10/site-packages/mackup/main.py", line 146, in main
    app.uninstall()
  File "/usr/local/Cellar/mackup/0.8.33/libexec/lib/python3.10/site-packages/mackup/application.py", line 264, in uninstall
    utils.copy(mackup_filepath, home_filepath)
  File "/usr/local/Cellar/mackup/0.8.33/libexec/lib/python3.10/site-packages/mackup/utils.py", line 90, in copy
    assert os.path.exists(src)
AssertionError
```
