### ISSUE TITLE
Can I skip some app's config ? I don't need them.

### ISSUE THREAD

**Issue by iSteveyang** [lra/mackup#1488]
Backing up .emacs.d ...
A folder named /Users/isteveyang/Library/Mobile Documents/com~apple~CloudDocs/Mackup/.emacs.d already exists in the backup.
Are you sure that you want to replace it ? <Yes|No>yes
Traceback (most recent call last):
  File "/usr/local/bin/mackup", line 11, in <module>
    load_entry_point('mackup==0.8.27', 'console_scripts', 'mackup')()
  File "/usr/local/Cellar/mackup/0.8.27/libexec/lib/python3.7/site-packages/mackup/main.py", line 88, in main
    app.backup()
  File "/usr/local/Cellar/mackup/0.8.27/libexec/lib/python3.7/site-packages/mackup/application.py", line 110, in backup
    utils.copy(home_filepath, mackup_filepath)
  File "/usr/local/Cellar/mackup/0.8.27/libexec/lib/python3.7/site-packages/mackup/utils.py", line 102, in copy
    shutil.copytree(src, dst)
  File "/usr/local/Cellar/mackup/0.8.27/libexec/lib/python3.7/shutil.py", line 368, in copytree
    raise Error(errors)
shutil.Error: [('/Users/isteveyang/.emacs.d/auto-save-list', '/Users/isteveyang/Library/Mobile Documents/com~apple~CloudDocs/Mackup/.emacs.d/auto-save-list', "[Errno 13] Permission denied: '/Users/isteveyang/.emacs.d/auto-save-list'")]

**Comment by iSteveyang** [comment]
There is too many configs in mackup list. I don't need them all. The emacs have the Permission denied error

**Comment by iSteveyang** [comment]
I uninstall it. Show the error 
```
Reverting .emacs.d ...
chmod: /Users/isteveyang/.emacs.d/auto-save-list: Permission denied
chflags: /Users/isteveyang/.emacs.d/auto-save-list: Permission denied
```

**Comment by jpmat296** [comment]
Dear iSteveyand

Here is what you're looking for:
https://github.com/lra/mackup/tree/master/doc#dont-sync-an-application

**Comment by iSteveyang** [comment]
Thank you
