### ISSUE TITLE
'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by tutelacooldouce** [lra/mackup#1523]
```
❯ mackup --version
Mackup 0.8.27
❯ python --version
Python 3.7.6
❯ cat .mackup.cfg
[storage]
engine = google_drive
❯ test -e  /Users/`whoami`/Google\ Drive/ ; echo $?
0
```
something wrong here? Did I miss something ? 

```
❯ mackup list
Traceback (most recent call last):
  File "/usr/local/bin/mackup", line 11, in <module>
    load_entry_point('mackup==0.8.27', 'console_scripts', 'mackup')()
  File "/usr/local/Cellar/mackup/0.8.27_1/libexec/lib/python3.8/site-packages/mackup/main.py", line 65, in main
    mckp = Mackup()
  File "/usr/local/Cellar/mackup/0.8.27_1/libexec/lib/python3.8/site-packages/mackup/mackup.py", line 24, in __init__
    self._config = config.Config()
  File "/usr/local/Cellar/mackup/0.8.27_1/libexec/lib/python3.8/site-packages/mackup/config.py", line 57, in __init__
    self._path = self._parse_path()
  File "/usr/local/Cellar/mackup/0.8.27_1/libexec/lib/python3.8/site-packages/mackup/config.py", line 214, in _parse_path
    path = get_google_drive_folder_location()
  File "/usr/local/Cellar/mackup/0.8.27_1/libexec/lib/python3.8/site-packages/mackup/utils.py", line 240, in get_google_drive_folder_location
    googledrive_home = str(data[0])
TypeError: 'NoneType' object is not subscriptable
```

**Comment by lra** [comment]
Not sure.
Where is your Google Drive config file? e.g. `Library/Application Support/Google/Drive/sync_config.db`

**Comment by tutelacooldouce** [comment]
here: Library/Application Support/Google/Drive/user_default/sync_config.db

**Comment by lra** [comment]
Should work: https://github.com/lra/mackup/blob/master/mackup/utils.py#L220

Until someone using Google Drive can test and debug this, I'm out of ideas.

**Comment by Ashtonian** [comment]
same issue, what do you need to debug ?

**Comment by tutelacooldouce** [comment]
for some reason,  I am able to list now, 
` ~ mackup list
..
..
..
454 applications supported in Mackup v0.8.27
`
can be closed my guess.

**Comment by lra** [comment]
Thanks!

**Comment by Joker-1991** [comment]
same issue too
