### ISSUE TITLE
Cannot backup insomnia

### ISSUE THREAD

**Issue by megawubs** [lra/mackup#1588]
When running `mackup backup` I get the following error when it tries to backup insomina:

```
Backing up Library/Application Support/Insomnia ...
Traceback (most recent call last):
  File "/usr/local/bin/mackup", line 11, in <module>
    load_entry_point('mackup==0.8.28', 'console_scripts', 'mackup')()
  File "/usr/local/Cellar/mackup/0.8.28_1/libexec/lib/python3.8/site-packages/mackup/main.py", line 88, in main
    app.backup()
  File "/usr/local/Cellar/mackup/0.8.28_1/libexec/lib/python3.8/site-packages/mackup/application.py", line 117, in backup
    utils.copy(home_filepath, mackup_filepath)
  File "/usr/local/Cellar/mackup/0.8.28_1/libexec/lib/python3.8/site-packages/mackup/utils.py", line 102, in copy
    shutil.copytree(src, dst)
  File "/usr/local/Cellar/mackup/0.8.28_1/libexec/lib/python3.8/shutil.py", line 554, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/usr/local/Cellar/mackup/0.8.28_1/libexec/lib/python3.8/shutil.py", line 510, in _copytree
    raise Error(errors)
shutil.Error: [('/[redacted]/Library/Application Support/Insomnia/SS', '/[redacted]/Library/Mobile Documents/com~apple~CloudDocs/Mackup/Library/Application Support/Insomnia/SS', "[Errno 102] Operation not supported on socket: '/[redacted]/Library/Application Support/Insomnia/SS'"), ('/[redacted]/Library/Application Support/Insomnia/SingletonCookie', '/[redacted]/Library/Mobile Documents/com~apple~CloudDocs/Mackup/Library/Application Support/Insomnia/SingletonCookie', "[Errno 2] No such file or directory: '/[redacted]/Library/Application Support/Insomnia/SingletonCookie'"), ('/[redacted]/Library/Application Support/Insomnia/SingletonLock', '/[redacted]/Library/Mobile Documents/com~apple~CloudDocs/Mackup/Library/Application Support/Insomnia/SingletonLock', "[Errno 2] No such file or directory: '/[redacted]/Library/Application Support/Insomnia/SingletonLock'")]
```

**Comment by lra** [comment]
There is a socket file in the folder to backup.
The only fix I see is to remove backup up the `Library/Application Support/Insomnia` and maybe add a more precise folder without the socket files.

Can't help as I'm not using the application.

Maybe see with the original contributor? https://github.com/lra/mackup/pull/1116 @browniebroke

**Comment by browniebroke** [comment]
I can't reproduce the error. I tried to update mackup via Homebrew, run backup several times with and without Insomnia open, every time it works fine for me.

**Comment by kamalhm** [comment]
I got the same issue, cant restore Insomnia from backup and got the exact same error

**Comment by mnlmaier** [comment]
error also showing up for me

**Comment by tan-zx** [comment]
for others who might come across this thread, I got the following error:

```
Backing up Library/Application Support/Insomnia ...
Traceback (most recent call last):
  File "/opt/homebrew/bin/mackup", line 33, in <module>
    sys.exit(load_entry_point('mackup==0.8.36', 'console_scripts', 'mackup')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/mackup/0.8.36/libexec/lib/python3.11/site-packages/mackup/main.py", line 93, in main
    app.backup()
  File "/opt/homebrew/Cellar/mackup/0.8.36/libexec/lib/python3.11/site-packages/mackup/application.py", line 117, in backup
    utils.copy(home_filepath, mackup_filepath)
  File "/opt/homebrew/Cellar/mackup/0.8.36/libexec/lib/python3.11/site-packages/mackup/utils.py", line 105, in copy
    shutil.copytree(src, dst)
  File "/opt/homebrew/Cellar/python@3.11/3.11.0/Frameworks/Python.framework/Versions/3.11/lib/python3.11/shutil.py", line 560, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.0/Frameworks/Python.framework/Versions/3.11/lib/python3.11/shutil.py", line 514, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/tanzx/Library/Application Support/Insomnia/SingletonSocket', '/Users/tanzx/Dropbox/Mackup/Library/Application Support/Insomnia/SingletonSocket', "[Errno 102] Operation not supported on socket: '/Users/tanzx/Library/Application Support/Insomnia/SingletonSocket'"), ('/Users/tanzx/Library/Application Support/Insomnia/SingletonCookie', '/Users/tanzx/Dropbox/Mackup/Library/Application Support/Insomnia/SingletonCookie', "[Errno 2] No such file or directory: '/Users/tanzx/Library/Application Support/Insomnia/SingletonCookie'"), ('/Users/tanzx/Library/Application Support/Insomnia/SingletonLock', '/Users/tanzx/Dropbox/Mackup/Library/Application Support/Insomnia/SingletonLock', "[Errno 2] No such file or directory: '/Users/tanzx/Library/Application Support/Insomnia/SingletonLock'")]
```

I went to the folder and saw that there are three files that are symlinked to files that do not exist. I'm not sure why these exist. The files are:
- `SingletonCookie`
- `SingletonLock`
- `SingletonSocket`

I managed to get `mackup backup -f` to complete after I deleted these three files but I'm not sure this is the right solution
