### ISSUE TITLE
.mackup.cfg

### ISSUE THREAD

**Issue by Le-Bowski** [lra/mackup#1595]
Hi,

After using .mackup.cfg this is what I get:

`Traceback (most recent call last):
  File "/usr/local/bin/mackup", line 11, in <module>
    load_entry_point('mackup==0.8.29', 'console_scripts', 'mackup')()
  File "/usr/local/Cellar/mackup/0.8.29/libexec/lib/python3.8/site-packages/mackup/main.py", line 66, in main
    mckp = Mackup()
  File "/usr/local/Cellar/mackup/0.8.29/libexec/lib/python3.8/site-packages/mackup/mackup.py", line 24, in __init__
    self._config = config.Config()
  File "/usr/local/Cellar/mackup/0.8.29/libexec/lib/python3.8/site-packages/mackup/config.py", line 46, in __init__
    self._parser = self._setup_parser(filename)
  File "/usr/local/Cellar/mackup/0.8.29/libexec/lib/python3.8/site-packages/mackup/config.py", line 151, in _setup_parser
    parser.read(os.path.join(os.path.join(os.environ["HOME"], filename)))
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/configparser.py", line 697, in read
    self._read(fp, filename)
  File "/usr/local/opt/python@3.8/Frameworks/Python.framework/Versions/3.8/lib/python3.8/configparser.py", line 1082, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: '/Users/antonio/.mackup.cfg', line: 1
'\ufeff[storage]\n'`

I've tried both iCould and local storage and the error stays the same.

**Comment by tillhainbach** [comment]
Can you update your issue with the contents of your .mackup.cfg file? Looks like something is wrong there (that's why you get a parsing-error).

**Comment by Crocmagnon** [comment]
The error says that the file misses a section header but I'd be tempted to say it contains a unicode BOM byte as the first character, making the line unparsable by mackup. See https://stackoverflow.com/a/17912811/2758732 for reference.

A quick workaround might be to add a newline or a comment at the beginning of the file but I don't know if this will work.
