### ISSUE TITLE
[HELP] section 'configuration_files' already exists

### ISSUE THREAD

**Issue by rlam3** [lra/mackup#1645]
Hi, 
Recently I tried to fetch master branch of this package via homebrew via the following comannd. 

```
brew install mackup --HEAD
```

Then afterwards I could not backup and arrived at the following traceback.. How do I fix this? 

```
❯ mackup backup -f -n -v
Traceback (most recent call last):
  File "/usr/local/bin/mackup", line 33, in <module>
    sys.exit(load_entry_point('mackup==0.8.29', 'console_scripts', 'mackup')())
  File "/usr/local/Cellar/mackup/HEAD-e71c129_1/libexec/lib/python3.9/site-packages/mackup/main.py", line 67, in main
    app_db = ApplicationsDatabase()
  File "/usr/local/Cellar/mackup/HEAD-e71c129_1/libexec/lib/python3.9/site-packages/mackup/appsdb.py", line 34, in __init__
    if config.read(config_file):
  File "/usr/local/Cellar/python@3.9/3.9.0/Frameworks/Python.framework/Versions/3.9/lib/python3.9/configparser.py", line 697, in read
    self._read(fp, filename)
  File "/usr/local/Cellar/python@3.9/3.9.0/Frameworks/Python.framework/Versions/3.9/lib/python3.9/configparser.py", line 1093, in _read
    raise DuplicateOptionError(sectname, optname,
configparser.DuplicateOptionError: While reading from '/usr/local/Cellar/mackup/HEAD-e71c129_1/libexec/lib/python3.9/site-packages/mackup/applications/webstorm.cfg' [line 38]: option 'Library/Application Support/WebStorm2019.3' in section 'configuration_files' already exists
```

**Comment by rlam3** [comment]
Reference: https://github.com/lra/mackup/pull/1628
