### ISSUE TITLE
Error running `mackup list`

### ISSUE THREAD

**Issue by crcastle** [lra/mackup#1677]
I just updated mackup using Homebrew, and now I'm getting the below error when I run `mackup list`. Version, OS details, and config below.

It looks like an error with IntelliJ, which I don't use nor believe I have ever installed on this machine (but I could be wrong).

```term
❯ mackup list
Traceback (most recent call last):
  File "/usr/local/bin/mackup", line 33, in <module>
    sys.exit(load_entry_point('mackup==0.8.31', 'console_scripts', 'mackup')())
  File "/usr/local/Cellar/mackup/0.8.31/libexec/lib/python3.9/site-packages/mackup/main.py", line 67, in main
    app_db = ApplicationsDatabase()
  File "/usr/local/Cellar/mackup/0.8.31/libexec/lib/python3.9/site-packages/mackup/appsdb.py", line 34, in __init__
    if config.read(config_file):
  File "/usr/local/Cellar/python@3.9/3.9.1_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/configparser.py", line 697, in read
    self._read(fp, filename)
  File "/usr/local/Cellar/python@3.9/3.9.1_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/configparser.py", line 1093, in _read
    raise DuplicateOptionError(sectname, optname,
configparser.DuplicateOptionError: While reading from '/usr/local/Cellar/mackup/0.8.31/libexec/lib/python3.9/site-packages/mackup/applications/intellijidea.cfg' [line 73]: option 'Library/Application Support/IdeaIC2017.1' in section 'configuration_files' already exists

~
❯ mackup --version
Mackup 0.8.31

~
❯ uname -a
Darwin MacBook-Pro 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64

~
❯ which mackup
/usr/local/bin/mackup

~
❯ cat .mackup.cfg
[storage]
enginer = dropbox
directory = Apps/Mackup

[applications_to_ignore]
ssh
aws
zsh
s3cmd
curl
```

![CleanShot 2021-01-03 at 19 54 48@2x](https://user-images.githubusercontent.com/275734/103493150-9d890780-4dfd-11eb-8650-7c0aa75fa9ad.png)

**Comment by elsefalse** [comment]
I got the same issue as well

**Comment by nnovaes** [comment]
i've got the same issue running `list` or `backup`... almost fresh OSX install, running catalina 10.15.7

```

 ~ % mackup --version
**Mackup 0.8.31**
 ~ % brew --version
**Homebrew 2.7.1**
Homebrew/homebrew-core (git revision 39af1; last commit 2021-01-04)
Homebrew/homebrew-cask (git revision 4e0ea; last commit 2021-01-04)
 ~ % mackup backup
Traceback (most recent call last):
  File "/usr/local/bin/mackup", line 33, in <module>
    sys.exit(load_entry_point('mackup==0.8.31', 'console_scripts', 'mackup')())
  File "/usr/local/Cellar/mackup/0.8.31/libexec/lib/python3.9/site-packages/mackup/main.py", line 67, in main
    app_db = ApplicationsDatabase()
  File "/usr/local/Cellar/mackup/0.8.31/libexec/lib/python3.9/site-packages/mackup/appsdb.py", line 34, in __init__
    if config.read(config_file):
  File "/usr/local/Cellar/python@3.9/3.9.1_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/configparser.py", line 697, in read
    self._read(fp, filename)
  File "/usr/local/Cellar/python@3.9/3.9.1_3/Frameworks/Python.framework/Versions/3.9/lib/python3.9/configparser.py", line 1093, in _read
    raise DuplicateOptionError(sectname, optname,
configparser.DuplicateOptionError: While reading from '/usr/local/Cellar/mackup/0.8.31/libexec/lib/python3.9/site-packages/mackup/applications/intellijidea.cfg' [line 73]: option 'Library/Application Support/IdeaIC2017.1' in section 'configuration_files' already exists
 ~ % 



```

**Comment by elsefalse** [comment]
once I clean up the duplicated items in https://github.com/lra/mackup/blob/master/mackup/applications/intellijidea.cfg, then `mackup` works again. I'm not sure why python package `configparser` will throw out that error after upgrading `mackup`, but I guess you can clean up the same file `/usr/local/Cellar/mackup/0.8.31/libexec/lib/python3.9/site-packages/mackup/applications/intellijidea.cfg` by deduplicating items of `[configuration_files]` inside that file to save your time before this issue gets resolved.

here is my example:
```
[application]
name = IntelliJ IDEA

[configuration_files]
.IntelliJIdea12/config
.IntelliJIdea13/config
.IntelliJIdea14/config
.IntelliJIdea15/config
IdeaIC2018.2/config
IdeaIC2018.3/config
IdeaIC2019.1/config
IdeaIC2019.2/config
IdeaIC2019.3/config
IntelliJIdea2016.1/config
IntelliJIdea2016.2/config
IntelliJIdea2016.3/config
IntelliJIdea2017.1/config
IntelliJIdea2017.2/config
IntelliJIdea2017.3/config
IntelliJIdea2018.1/config
IntelliJIdea2018.2/config
IntelliJIdea2018.3/config
IntelliJIdea2019.1/config
IntelliJIdea2019.2/config
IntelliJIdea2019.3/config
Library/Application Support/IdeaIC2016.1
Library/Application Support/IdeaIC2017.1
Library/Application Support/IdeaIC2017.2
Library/Application Support/IdeaIC2017.3
Library/Application Support/IdeaIC2018.2
Library/Application Support/IdeaIC2018.3
Library/Application Support/IdeaIC2019.1
Library/Application Support/IntelliJIdea12
Library/Application Support/IntelliJIdea13
Library/Application Support/IntelliJIdea14
Library/Application Support/IntelliJIdea15
Library/Application Support/IntelliJIdea2016.1
Library/Application Support/IntelliJIdea2016.2
Library/Application Support/IntelliJIdea2016.3
Library/Application Support/IntelliJIdea2017.1
Library/Application Support/IntelliJIdea2017.2
Library/Application Support/IntelliJIdea2017.3
Library/Application Support/IntelliJIdea2018.1
Library/Application Support/IntelliJIdea2018.2
Library/Application Support/IntelliJIdea2018.3
Library/Application Support/IntelliJIdea2019.1
Library/Application Support/IntelliJIdea2019.2
Library/Application Support/IntelliJIdea2019.3
Library/Application Support/JetBrains/IntelliJIdea2020.1
Library/Preferences/IdeaIC2016.1
Library/Preferences/IdeaIC2016.2
Library/Preferences/IdeaIC2016.3
Library/Preferences/IdeaIC2017.1
Library/Preferences/IdeaIC2017.2
Library/Preferences/IdeaIC2017.3
Library/Preferences/IdeaIC2018.2
Library/Preferences/IdeaIC2018.3
Library/Preferences/IdeaIC2019.1
Library/Preferences/IntelliJIdea12
Library/Preferences/IntelliJIdea13
Library/Preferences/IntelliJIdea14
Library/Preferences/IntelliJIdea15
Library/Preferences/IntelliJIdea2016.1
Library/Preferences/IntelliJIdea2016.2
Library/Preferences/IntelliJIdea2016.3
Library/Preferences/IntelliJIdea2017.1
Library/Preferences/IntelliJIdea2017.2
Library/Preferences/IntelliJIdea2017.3
Library/Preferences/IntelliJIdea2018.1
Library/Preferences/IntelliJIdea2018.2
Library/Preferences/IntelliJIdea2018.3
Library/Preferences/IntelliJIdea2019.1
Library/Preferences/IntelliJIdea2019.2
Library/Preferences/IntelliJIdea2019.3
```

**Comment by nnovaes** [comment]
yeap, it works! thanks

**Comment by lra** [comment]
Thanks for the report, confirmed, will push a release soon.
