### ISSUE TITLE
A file named ~/Dropbox/Mackup/.config/hub already exists in the backup.

### ISSUE THREAD

**Issue by vfonic** [lra/mackup#1693]
I just ran `mackup backup` before I'm about to reinstall macOS.

I got this message:

> Backing up .config/hub ...
A file named /Users/viktor/Dropbox/Mackup/.config/hub already exists in the backup.
Are you sure that you want to replace it ? <Yes|No>Yes

I opened a new terminal window and ran `ls -l | grep config` and I got this back:
`lrwxr-xr-x    36 viktor 15 Sep  2020  .config -> /Users/viktor/Dropbox/Mackup/.config`

So, Mackup already backed up everything in `.config`, but it still cannot figure out that it's trying to backup already backed-up file/folder.

Both `~/.config/hub` and `~/Dropbox/Mackup/.config/hub` are the same file.

I'm going to type in "Yes" and see what happens.

...aaand it failed. :)

Here's the error output, I hope that helps:

```
Traceback (most recent call last):
  File "/usr/local/bin/mackup", line 33, in <module>
    sys.exit(load_entry_point('mackup==0.8.32', 'console_scripts', 'mackup')())
  File "/usr/local/Cellar/mackup/0.8.32/libexec/lib/python3.9/site-packages/mackup/main.py", line 93, in main
    app.backup()
  File "/usr/local/Cellar/mackup/0.8.32/libexec/lib/python3.9/site-packages/mackup/application.py", line 110, in backup
    utils.copy(home_filepath, mackup_filepath)
  File "/usr/local/Cellar/mackup/0.8.32/libexec/lib/python3.9/site-packages/mackup/utils.py", line 90, in copy
    assert os.path.exists(src)
AssertionError
```

Mackup 0.8.32

**Comment by joshmedeski** [comment]
The `~/.config` directory should not be symbolically linked for mackup to work.

I recommend checking any custom `~/.mackup/*.cfg` files or the main `~/.mackup.cfg` file to make sure you have not added `config` to any of your settings.

Please remove the symbolic link:
```sh
rm ~/.config
```

And rerun mackup:
```sh
mackup restore
```

This will restore all your config files correctly and properly back up hub.

p.s. GitHub built their own [official cli](https://github.com/cli/cli). It's worth checking out. I replaced this with hub about when the `gh` cli came out and I'm happy with it (mackup supports it too!).

**Comment by vfonic** [comment]
Thanks @joshmedeski!

I know about gh CLI, but hub served me well so far so I don't see a need to switch atm.

I _guess_ I might have backed up (symlinked) `~/.config` manually. I think the biggest fear with mackup is uncertainty of what is actually happening / what is going to happen.

Perhaps this image explains the best the beautiful UX this tool could have:
<img src="http://i.imgur.com/HmVMvYc.png" alt="yarn-update" width="386">

I'm not very familiar with python, but if there are some parts I can help with, let me know.

**Comment by joshmedeski** [comment]
Good idea @vfonic, I mentioned your idea in another [conversation](https://github.com/lra/mackup/issues/1127) so we'll see how mackup can be improved.

Did removing the symlink and rerunning mackup work for you?

**Comment by vfonic** [comment]
It did. Thank you, @joshmedeski!
