### ISSUE TITLE
Cannot uninstall on Big Sur 11.4 m1

### ISSUE THREAD

**Issue by micweeks** [lra/mackup#1743]
I'm trying to restore back all the dotfiles and settings since iTerm2 and other software all keep resetting the preferences, but can't: 

```zsh
[daniyar:~] [base] % mackup uninstall
You are going to uninstall Mackup.
Every configuration file, setting and dotfile managed by Mackup will be unlinked and moved back to their original place, in your home folder.
Are you sure ? <Yes|No>yes
Reverting Library/Preferences/com.apple.Music.eq.plist ...
Reverting Library/Preferences/com.apple.Music.plist ...
Reverting .atom/config.cson ...
Reverting Library/Preferences/com.github.atom.plist ...
Reverting .bash_profile ...
Reverting Library/Preferences/calibre ...
Traceback (most recent call last):
  File "/opt/homebrew/bin/mackup", line 33, in <module>
    sys.exit(load_entry_point('mackup==0.8.32', 'console_scripts', 'mackup')())
  File "/opt/homebrew/Cellar/mackup/0.8.32/libexec/lib/python3.9/site-packages/mackup/main.py", line 146, in main
    app.uninstall()
  File "/opt/homebrew/Cellar/mackup/0.8.32/libexec/lib/python3.9/site-packages/mackup/application.py", line 264, in uninstall
    utils.copy(mackup_filepath, home_filepath)
  File "/opt/homebrew/Cellar/mackup/0.8.32/libexec/lib/python3.9/site-packages/mackup/utils.py", line 105, in copy
    shutil.copytree(src, dst)
  File "/opt/homebrew/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/shutil.py", line 557, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/opt/homebrew/Cellar/python@3.9/3.9.5/Frameworks/Python.framework/Versions/3.9/lib/python3.9/shutil.py", line 513, in _copytree
    raise Error(errors)
shutil.Error: [('/Volumes/GoogleDrive/My Drive/backup/mackup_air/Mackup/Library/Preferences/calibre/gui.json', '/Users/daniyar/Library/Preferences/calibre/gui.json', "[Errno 1] Operation not permitted: '/Users/daniyar/Library/Preferences/calibre/gui.json'"), ('/Volumes/GoogleDrive/My Drive/backup/mackup_air/Mackup/Library/Preferences/calibre/dynamic.pickle.json', '/Users/daniyar/Library/Preferences/calibre/dynamic.pickle.json', "[Errno 1] Operation not permitted: '/Users/daniyar/Library/Preferences/calibre/dynamic.pickle.json'"), ('/Volumes/GoogleDrive/My Drive/backup/mackup_air/Mackup/Library/Preferences/calibre/plugins/KFX Input.zip', '/Users/daniyar/Library/Preferences/calibre/plugins/KFX Input.zip', "[Errno 1] Operation not permitted: '/Users/daniyar/Library/Preferences/calibre/plugins/KFX Input.zip'"), ('/Volumes/GoogleDrive/My Drive/backup/mackup_air/Mackup/Library/Preferences/calibre/plugins/DeDRM.zip', '/Users/daniyar/Library/Preferences/calibre/plugins/DeDRM.zip', "[Errno 1] Operation not permitted: '/Users/daniyar/Library/Preferences/calibre/plugins/DeDRM.zip'"), ('/Volumes/GoogleDrive/My Drive/backup/mackup_air/Mackup/Library/Preferences/calibre/plugins/dedrm.json', '/Users/daniyar/Library/Preferences/calibre/plugins/dedrm.json', "[Errno 1] Operation not permitted: '/Users/daniyar/Library/Preferences/calibre/plugins/dedrm.json'"), ('/Volumes/GoogleDrive/My Drive/backup/mackup_air/Mackup/Library/Preferences/calibre/plugins/DeDRM/libraryfiles/libalfcrypto.dylib', '/Users/daniyar/Library/Preferences/calibre/plugins/DeDRM/libraryfiles/libalfcrypto.dylib', "[Errno 1] Operation not permitted: '/Users/daniyar/Library/Preferences/calibre/plugins/DeDRM/libraryfiles/libalfcrypto.dylib'"), ('/Volumes/GoogleDrive/My Drive/backup/mackup_air/Mackup/Library/Preferences/calibre/plugins/DeDRM/help/DeDRM_EInk Kindle Serial Number_Help.htm', '/Users/daniyar/Library/Preferences/calibre/plugins/DeDRM/help/DeDRM_EInk Kindle Serial Number_Help.htm', "[Errno 1] Operation not permitted: '/Users/daniyar/Library/Preferences/calibre/plugins/DeDRM/help/DeDRM_EInk Kindle Serial Number_Help.htm'"), ('/Volumes/GoogleDrive/My Drive/backup/mackup_air/Mackup/Library/Preferences/calibre/resources/images/mimetypes/kfx.png', '/Users/daniyar/Library/Preferences/calibre/resources/images/mimetypes/kfx.png', "[Errno 1] Operation not permitted: '/Users/daniyar/Library/Preferences/calibre/resources/images/mimetypes/kfx.png'"), ('/Volumes/GoogleDrive/My Drive/backup/mackup_air/Mackup/Library/Preferences/calibre/global.py.json', '/Users/daniyar/Library/Preferences/calibre/global.py.json', "[Errno 1] Operation not permitted: '/Users/daniyar/Library/Preferences/calibre/global.py.json'"), ('/Volumes/GoogleDrive/My Drive/backup/mackup_air/Mackup/Library/Preferences/calibre/conversion/toc.py', '/Users/daniyar/Library/Preferences/calibre/conversion/toc.py', "[Errno 1] Operation not permitted: '/Users/daniyar/Library/Preferences/calibre/conversion/toc.py'"), ('/Volumes/GoogleDrive/My Drive/backup/mackup_air/Mackup/Library/Preferences/calibre/conversion/metadata.py', '/Users/daniyar/Library/Preferences/calibre/conversion/metadata.py', "[Errno 1] Operation not permitted: '/Users/daniyar/Library/Preferences/calibre/conversion/metadata.py'"), ('/Volumes/GoogleDrive/My Drive/backup/mackup_air/Mackup/Library/Preferences/calibre/conversion/heuristics.py', '/Users/daniyar/Library/Preferences/calibre/conversion/heuristics.py', "[Errno 1] Operation not permitted: '/Users/daniyar/Library/Preferences/calibre/conversion/heuristics.py'"), ('/Volumes/GoogleDrive/My Drive/backup/mackup_air/Mackup/Library/Preferences/calibre/conversion/search_and_replace.py', '/Users/daniyar/Library/Preferences/calibre/conversion/search_and_replace.py', "[Errno 1] Operation not permitted: '/Users/daniyar/Library/Preferences/calibre/conversion/search_and_replace.py'"), ('/Volumes/GoogleDrive/My Drive/backup/mackup_air/Mackup/Library/Preferences/calibre/conversion/fb2_output.py', '/Users/daniyar/Library/Preferences/calibre/conversion/fb2_output.py', "[Errno 1] Operation not permitted: '/Users/daniyar/Library/Preferences/calibre/conversion/fb2_output.py'"), ('/Volumes/GoogleDrive/My Drive/backup/mackup_air/Mackup/Library/Preferences/calibre/conversion/kfx_input.py', '/Users/daniyar/Library/Preferences/calibre/conversion/kfx_input.py', "[Errno 1] Operation not permitted: '/Users/daniyar/Library/Preferences/calibre/conversion/kfx_input.py'"), ('/Volumes/GoogleDrive/My Drive/backup/mackup_air/Mackup/Library/Preferences/calibre/conversion/comic_input.py', '/Users/daniyar/Library/Preferences/calibre/conversion/comic_input.py', "[Errno 1] Operation not permitted: '/Users/daniyar/Library/Preferences/calibre/conversion/comic_input.py'"), ('/Volumes/GoogleDrive/My Drive/backup/mackup_air/Mackup/Library/Preferences/calibre/conversion/debug.py', '/Users/daniyar/Library/Preferences/calibre/conversion/debug.py', "[Errno 1] Operation not permitted: '/Users/daniyar/Library/Preferences/calibre/conversion/debug.py'"), ('/Volumes/GoogleDrive/My Drive/backup/mackup_air/Mackup/Library/Preferences/calibre/conversion/epub_output.py', '/Users/daniyar/Library/Preferences/calibre/conversion/epub_output.py', "[Errno 1] Operation not permitted: '/Users/daniyar/Library/Preferences/calibre/conversion/epub_output.py'"), ('/Volumes/GoogleDrive/My Drive/backup/mackup_air/Mackup/Library/Preferences/calibre/conversion/page_setup.py', '/Users/daniyar/Library/Preferences/calibre/conversion/page_setup.py', "[Errno 1] Operation not permitted: '/Users/daniyar/Library/Preferences/calibre/conversion/page_setup.py'"), ('/Volumes/GoogleDrive/My Drive/backup/mackup_air/Mackup/Library/Preferences/calibre/conversion/look_and_feel.py', '/Users/daniyar/Library/Preferences/calibre/conversion/look_and_feel.py', "[Errno 1] Operation not permitted: '/Users/daniyar/Library/Preferences/calibre/conversion/look_and_feel.py'"), ('/Volumes/GoogleDrive/My Drive/backup/mackup_air/Mackup/Library/Preferences/calibre/conversion/structure_detection.py', '/Users/daniyar/Library/Preferences/calibre/conversion/structure_detection.py', "[Errno 1] Operation not permitted: '/Users/daniyar/Library/Preferences/calibre/conversion/structure_detection.py'"), ('/Volumes/GoogleDrive/My Drive/backup/mackup_air/Mackup/Library/Preferences/calibre/gui.py.json', '/Users/daniyar/Library/Preferences/calibre/gui.py.json', "[Errno 1] Operation not permitted: '/Users/daniyar/Library/Preferences/calibre/gui.py.json'"), ('/Volumes/GoogleDrive/My Drive/backup/mackup_air/Mackup/Library/Preferences/calibre/customize.py.json', '/Users/daniyar/Library/Preferences/calibre/customize.py.json', "[Errno 1] Operation not permitted: '/Users/daniyar/Library/Preferences/calibre/customize.py.json'"), ('/Volumes/GoogleDrive/My Drive/backup/mackup_air/Mackup/Library/Preferences/calibre/fonts/scanner_cache.json', '/Users/daniyar/Library/Preferences/calibre/fonts/scanner_cache.json', "[Errno 1] Operation not permitted: '/Users/daniyar/Library/Preferences/calibre/fonts/scanner_cache.json'")]
```

Using Mackup 0.8.32

**Comment by joshmedeski** [comment]
Looks like it could be permission issues from some of your files.

**Comment by elmpp** [comment]
I also get this error
