### ISSUE TITLE
Cannot uninstall on macOS Monterey 12.1 - mackup 0.8.33

### ISSUE THREAD

**Issue by svenstehle** [lra/mackup#1795]
Hi, I want to remove some files from my mackup using the ~/.mackup.cfg  - it did not remove them from the cloud storage automatically and restore them on my machine. So I thought I'd give `mackup uninstall` a shot.

Unfortunately, after it reverted a few entries, this is the verbose result. I replaced my username with `<username>`:

```python
--- sublime-text-3 ---
Doing nothing, /Users/<username>/Google Drive/My Drive/Mackup/.config/sublime-text-3/Packages/User does not exist
Reverting /Users/<username>/Google Drive/My Drive/Mackup/Library/Application Support/Sublime Text 3/Packages/User
  at /Users/<username>/Library/Application Support/Sublime Text 3/Packages/User ...
Traceback (most recent call last):
  File "/usr/local/bin/mackup", line 33, in <module>
    sys.exit(load_entry_point('mackup==0.8.33', 'console_scripts', 'mackup')())
  File "/usr/local/Cellar/mackup/0.8.33/libexec/lib/python3.10/site-packages/mackup/main.py", line 146, in main
    app.uninstall()
  File "/usr/local/Cellar/mackup/0.8.33/libexec/lib/python3.10/site-packages/mackup/application.py", line 264, in uninstall
    utils.copy(mackup_filepath, home_filepath)
  File "/usr/local/Cellar/mackup/0.8.33/libexec/lib/python3.10/site-packages/mackup/utils.py", line 105, in copy
    shutil.copytree(src, dst)
  File "/usr/local/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/shutil.py", line 556, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/usr/local/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/shutil.py", line 512, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/<username>/Google Drive/My Drive/Mackup/Library/Application Support/Sublime Text 3/Packages/User/KiteSublime.sublime-settings', '/Users/<username>/Library/Application Support/Sublime Text 3/Packages/User/KiteSublime.sublime-settings', "[Errno 1] Operation not permitted: '/Users/<username>/Library/Application Support/Sublime Text 3/Packages/User/KiteSublime.sublime-settings'")]
```

I am afraid to force `mackup --root --force uninstall` ... should I ??? I don't want to break all my configuration. How can I fix this situation

**Comment by svenstehle** [comment]
The same goes for `.aws`... I removed it again from the ignore list in ~/.mackup.cfg:

```python
Reverting Library/Preferences/com.apple.Music.plist ...
Reverting Library/Preferences/com.apple.Music.eq.plist ...
Reverting .aws ...
Traceback (most recent call last):
  File "/usr/local/bin/mackup", line 33, in <module>
    sys.exit(load_entry_point('mackup==0.8.33', 'console_scripts', 'mackup')())
  File "/usr/local/Cellar/mackup/0.8.33/libexec/lib/python3.10/site-packages/mackup/main.py", line 146, in main
    app.uninstall()
  File "/usr/local/Cellar/mackup/0.8.33/libexec/lib/python3.10/site-packages/mackup/application.py", line 264, in uninstall
    utils.copy(mackup_filepath, home_filepath)
  File "/usr/local/Cellar/mackup/0.8.33/libexec/lib/python3.10/site-packages/mackup/utils.py", line 105, in copy
    shutil.copytree(src, dst)
  File "/usr/local/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/shutil.py", line 556, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/usr/local/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/shutil.py", line 512, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/<username>/Google Drive/My Drive/Mackup/.aws/config', '/Users/<username>/.aws/config', "[Errno 1] Operation not permitted: '/Users/<username>/.aws/config'"), ('/Users/<username>/Google Drive/My Drive/Mackup/.aws/get_session_token.sh', '/Users/<username>/.aws/get_session_token.sh', "[Errno 1] Operation not permitted: '/Users/<username>/.aws/get_session_token.sh'"), ('/Users/<username>/Google Drive/My Drive/Mackup/.aws/get_session_token_test.sh', '/Users/<username>/.aws/get_session_token_test.sh', "[Errno 1] Operation not permitted: '/Users/<username>/.aws/get_session_token_test.sh'"), ('/Users/<username>/Google Drive/My Drive/Mackup/.aws/credentials', '/Users/<username>/.aws/credentials', "[Errno 1] Operation not permitted: '/Users/<username>/.aws/credentials'")]
```
