### ISSUE TITLE
"mackup uninstall" failed with Google Drive Desktop (=File Stream)

### ISSUE THREAD

**Issue by kosukemori** [lra/mackup#1796]
## Environment
- macOS 12.1
- Mackup 0.8.33

## Problem
`mackup uninstall[-f]` failed with Google Drive Desktop (Formerly Google File Stream).

My  `~/.mackup.cfg`:
```
[storage]
engine = file_system
path = Google Drive/My Drive
directory = appfiles/Mackup
```

Log:
```
$ mackup uninstall -f
...
Reverting .config/fish ...
Traceback (most recent call last):
  File "/usr/local/bin/mackup", line 33, in <module>
    sys.exit(load_entry_point('mackup==0.8.33', 'console_scripts', 'mackup')())
  File "/usr/local/Cellar/mackup/0.8.33/libexec/lib/python3.10/site-packages/mackup/main.py", line 146, in main
    app.uninstall()
  File "/usr/local/Cellar/mackup/0.8.33/libexec/lib/python3.10/site-packages/mackup/application.py", line 264, in uninstall
    utils.copy(mackup_filepath, home_filepath)
  File "/usr/local/Cellar/mackup/0.8.33/libexec/lib/python3.10/site-packages/mackup/utils.py", line 105, in copy
    shutil.copytree(src, dst)
  File "/usr/local/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/shutil.py", line 556, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/usr/local/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/shutil.py", line 512, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/foobar/Google Drive/My Drive/appfiles/Mackup/.config/fish/fish_variables', '/Users/foobar/.config/fish/fish_variables', "[Errno 1] Operation not permitted: '/Users/foobar/.config/fish/fish_variables'"), ....]
```

It seems that `shutil.copytree()` failed when it try to copy metadata.

## Workaround
Edit `$(brew --prefix)/Cellar/mackup/<mackup-version>/libexec/lib/python<python-version>/site-packages/mackup/utils.py`as below. As a result, we lose metadata about directory, but it's not so much problem right now.

```
105c105
<         shutil.copytree(src, dst)
---
>         shutil.copytree(src, dst, copy_function=copy)
```

**Comment by jwlawrence** [comment]
Thanks for the workaround @kosukemori I was completely blocked without it.
