### ISSUE TITLE
mackup backup failing on MacOS 12.2 Beta

### ISSUE THREAD

**Issue by qwinters** [lra/mackup#1797]
I'm trying to backup several apps using `mackup backup` with a fairly simple config on an M1 Mac running 12.2 Beta version of MacOS Monterey and I'm seeing this error

```shell 
qwinters@qwinters-m1 (base) 1 ❯ mackup backup                                                                                            
Backing up Library/Application Support/Übersicht/widgets ...
A folder named /Users/qwinters/.local/share/chezmoi/dot_mackup/Library/Application Support/Übersicht/widgets already exists in the backup.
Are you sure that you want to replace it? <Yes|No> Yes
Traceback (most recent call last):
  File "/opt/homebrew/bin/mackup", line 33, in <module>
    sys.exit(load_entry_point('mackup==0.8.33', 'console_scripts', 'mackup')())
  File "/opt/homebrew/Cellar/mackup/0.8.33/libexec/lib/python3.10/site-packages/mackup/main.py", line 93, in main
    app.backup()
  File "/opt/homebrew/Cellar/mackup/0.8.33/libexec/lib/python3.10/site-packages/mackup/application.py", line 110, in backup
    utils.copy(home_filepath, mackup_filepath)
  File "/opt/homebrew/Cellar/mackup/0.8.33/libexec/lib/python3.10/site-packages/mackup/utils.py", line 105, in copy
    shutil.copytree(src, dst)
  File "/opt/homebrew/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/shutil.py", line 556, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/opt/homebrew/Cellar/python@3.10/3.10.1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/shutil.py", line 512, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/qwinters/Library/Application Support/Übersicht/widgets/pecan/pecan.css', '/Users/qwinters/.local/share/chezmoi/dot_mackup/Library/Application Support/Übersicht/widgets/pecan/pecan.css', "[Errno 2] No such file or directory: '/Users/qwinters/Library/Application Support/Übersicht/widgets/pecan/pecan.css'")]
```
I've confirmed that some of the paths do in fact exist (as symlinks) for example

```shell
qwinters@qwinters-m1 (base) ❯ ls /Users/qwinters/Library/Application\ Support/Übersicht/widgets/pecan/pecan.css                           
/Users/qwinters/Library/Application Support/Übersicht/widgets/pecan/pecan.css -> /Users/qwinters/.config/pecan.css
```
Any advice would be appreciated!!

Config is available [here](https://github.com/qwinters/dotfiles/blob/1bcb8c3bf05855c63636cdc2c805dbe76a823c4a/dot_mackup.cfg)

**Comment by spuder** [comment]
Possibly related

https://github.com/lra/mackup/issues/1924
