### ISSUE TITLE
Espanso makes mackup crash

### ISSUE THREAD

**Issue by kud** [lra/mackup#1868]
```
Backing up Library/Application Support/espanso ...
Traceback (most recent call last):
  File "/usr/local/bin/mackup", line 33, in <module>
    sys.exit(load_entry_point('mackup==0.8.35', 'console_scripts', 'mackup')())
  File "/usr/local/Cellar/mackup/0.8.35/libexec/lib/python3.10/site-packages/mackup/main.py", line 93, in main
    app.backup()
  File "/usr/local/Cellar/mackup/0.8.35/libexec/lib/python3.10/site-packages/mackup/application.py", line 117, in backup
    utils.copy(home_filepath, mackup_filepath)
  File "/usr/local/Cellar/mackup/0.8.35/libexec/lib/python3.10/site-packages/mackup/utils.py", line 105, in copy
    shutil.copytree(src, dst)
  File "/usr/local/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/shutil.py", line 558, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/usr/local/Cellar/python@3.10/3.10.7/Frameworks/Python.framework/Versions/3.10/lib/python3.10/shutil.py", line 512, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/kud/Library/Application Support/espanso/espansoworkerv2.sock', '/Users/kud/pCloud/Mackup/Library/Application Support/espanso/espansoworkerv2.sock', "[Errno 102] Operation not supported on socket: '/Users/kud/Library/Application Support/espanso/espansoworkerv2.sock'"), ('/Users/kud/Library/Application Support/espanso/espansodaemonv2.sock', '/Users/kud/pCloud/Mackup/Library/Application Support/espanso/espansodaemonv2.sock', "[Errno 102] Operation not supported on socket: '/Users/kud/Library/Application Support/espanso/espansodaemonv2.sock'"), ('/Users/kud/Library/Application Support/espanso/espanso.sock', '/Users/kud/pCloud/Mackup/Library/Application Support/espanso/espanso.sock', "[Errno 102] Operation not supported on socket: '/Users/kud/Library/Application Support/espanso/espanso.sock'"), ('/Users/kud/Library/Application Support/espanso/worker.sock', '/Users/kud/pCloud/Mackup/Library/Application Support/espanso/worker.sock', "[Errno 102] Operation not supported on socket: '/Users/kud/Library/Application Support/espanso/worker.sock'")]
```

**Comment by jaklan** [comment]
Duplicate: https://github.com/lra/mackup/issues/1850
