### ISSUE TITLE
ImportError: No module named _sqlite3

### ISSUE THREAD

**Issue by JacopKane** [lra/mackup#220]
On a fresh homebrew install i'm getting these errors:

``` cmd
$ mackup
Traceback (most recent call last):
  File "/usr/local/bin/mackup", line 22, in <module>
    import mackup.main
  File "/usr/local/lib/python2.7/site-packages/mackup/main.py", line 22, in <module>
    from .application import ApplicationProfile
  File "/usr/local/lib/python2.7/site-packages/mackup/application.py", line 7, in <module>
    from .mackup import Mackup
  File "/usr/local/lib/python2.7/site-packages/mackup/mackup.py", line 11, in <module>
    from . import utils
  File "/usr/local/lib/python2.7/site-packages/mackup/utils.py", line 10, in <module>
    import sqlite3
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/sqlite3/__init__.py", line 24, in <module>
    from dbapi2 import *
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: No module named _sqlite3
```

**Comment by praveshjain** [comment]
I am facing the same issue. But none of the solutions work for me. I am running scrapy and I get the error : 

2015-11-16 20:03:31 [twisted] CRITICAL: Unhandled error in Deferred:
...
...
exceptions.ImportError: No module named _sqlite3.

find /usr/local -name _sqlite3.so returns:
/usr/local/Cellar/python/2.7.10_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload/_sqlite3.so

Any ideas?

**Comment by FrancisShi** [comment]
Thanks to @lra . brew uninstall python,and brew install python fix mine

**Comment by lxw0109** [comment]
Got the same error as @praveshjain .  Any ideas?

**Comment by praveshjain** [comment]
@lxw0109 I do not remember what worked for me. Damn! That's why you document.

**Comment by lxw0109** [comment]
According to [this question](http://stackoverflow.com/questions/1210664/no-module-named-sqlite3), I installed `libsqlite3-dev` and recompiled Python, it works.
>Install `sqlite-devel` (or `libsqlite3-dev` on some Debian-based systems)
>re-configured and re-compiled Python with `./configure --enable-loadable-sqlite-extensions && make && sudo make install`

BTW, I'm using Python3.6.1

**Comment by elhigu** [comment]
`brew upgrade python` was enough to fix this for me.
