### ISSUE TITLE
How to handle mackup updates?

### ISSUE THREAD

**Issue by franciscolourenco** [lra/mackup#229]
There are a few problems which might occur when updating mackup.

For example, after I updated to the mackup version which removed support for Ember.app, I ran uninstall, however ember directory was not restored.

Shouldn't mackup restore files based on the files currently in ~/Dropbox/Mackup, instead of using config files which might have new directives or not be there anymore?

Another problem arrises when an app config changes. How can the new config be applied? It seems running uninstall, deleting the folder and backup again would put things in order, so.. maybe mackup should have a update/refresh command?

**Comment by kishansairam9** [comment]
> For the ones who come here, if upgrading mackup breaks your config, because the list of synced files for your app changes, the safest way to upgrade is to:
> On your main workstation:
> 
> 1. mackup uninstall
> 2. Upgrade mackup
> 3. mackup backup
> 
> And on your other workstations:
> 
> 1. mackup uninstall
> 2. Upgrade mackup
> 3. mackup restore
> 
> A bit of a pain, but until we come up with a solid plan, I don't see a better way =(

I have came to this discussion from #621

I have no luck in doing `mackup uninstall`
```zsh
~
❯ mackup uninstall
You are going to uninstall Mackup.
Every configuration file, setting and dotfile managed by Mackup will be unlinked and moved back to their original place, in your home folder.
Are you sure ? <Yes|No>Yes
Traceback (most recent call last):
  File "/usr/local/bin/mackup", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/mackup/main.py", line 144, in main
    verbose)
  File "/usr/local/lib/python3.7/site-packages/mackup/application.py", line 26, in __init__
    assert isinstance(files, set)
AssertionError
```

I also don't have backup of things.
Could you please suggest me a way to get Mackup back working @lra ?
