### ISSUE TITLE
Mackup won't restore

### ISSUE THREAD

**Issue by mattijsbliek** [lra/mackup#292]
I had two systems running in sync through Dropbox, but wanted to change the file_system. I did this on computer 1. On computer 2 I ran `mackup uninstall`, copied over .mackup.cfg from the other computer, and ran `mackup restore`. But I'm running into the following error:
```
Restoring Library/Application Support/Sublime Text 3/Packages/User...
Traceback (most recent call last):
  File "/usr/local/bin/mackup", line 26, in <module>
    mackup.main.main()
  File "/usr/local/Cellar/mackup/0.7.3/lib/python2.7/site-packages/mackup/main.py", line 56, in main
    app.restore()
  File "/usr/local/Cellar/mackup/0.7.3/lib/python2.7/site-packages/mackup/application.py", line 149, in restore
    utils.link(mackup_filepath, home_filepath)
  File "/usr/local/Cellar/mackup/0.7.3/lib/python2.7/site-packages/mackup/utils.py", line 123, in link
    os.makedirs(abs_path)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: '/Users/Mattijs/Library/Application Support/Sublime Text 3/Packages'
```

My guess is that it won't overwrite, but I would like Mackup to take all the files from the backup directory, and overwrite those on my system. Is there any way I can do this?

**Comment by lra** [comment]
I guess you can point mackup to another storage, do a `backup` to create all the links, change mackup to use your legit engine, and do a mackup restore to overwrite all the links mackup created.
