### ISSUE TITLE
Skype backup crashes with [Errno 102] Operation not supported on socket

### ISSUE THREAD

**Issue by paulpref** [lra/mackup#324]
Hello, I’ve just started using mackup (0.7.3) and I love it! I’ve removed Skype (Version 6.19 (442), on OS X 10.9.4)) for now, but mackup crashes trying to copy the `com.skype.skypePostUpgradeLauncher.socket` socket file.

```
Backing up Library/Application Support/Skype...
Traceback (most recent call last):
  File "/usr/local/bin/mackup", line 26, in <module>
    mackup.main.main()
  File "/usr/local/Cellar/mackup/0.7.3/lib/python2.7/site-packages/mackup/main.py", line 48, in main
    app.backup()
  File "/usr/local/Cellar/mackup/0.7.3/lib/python2.7/site-packages/mackup/application.py", line 90, in backup
    utils.copy(filepath, mackup_filepath)
  File "/usr/local/Cellar/mackup/0.7.3/lib/python2.7/site-packages/mackup/utils.py", line 91, in copy
    shutil.copytree(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 208, in copytree
    raise Error, errors
shutil.Error: [('/Users/user/Library/Application Support/Skype/Upgrade/com.skype.skypePostUpgradeLauncher.socket', '/Users/user/Dropbox/Applications/Mackup/Library/Application Support/Skype/Upgrade/com.skype.skypePostUpgradeLauncher.socket', "[Errno 102] Operation not supported on socket: '/Users/user/Library/Application Support/Skype/Upgrade/com.skype.skypePostUpgradeLauncher.socket'")]
```

**Comment by sarbogast** [comment]
Same here

**Comment by spencergibb** [comment]
+1

**Comment by lra** [comment]
You mean it crashes because you've removed Skype?

**Comment by spencergibb** [comment]
yes, I had to close skype and delete that socket file before it would proceed

**Comment by spencergibb** [comment]
maybe you could use `shutil.ignore_patterns(*patterns)` to ignore `*.socket` and pass that to `shutil.copytree`

**Comment by lra** [comment]
I don't think we can hardcode such things in mackup, any other app could have a legitimate .socket file

**Comment by spencergibb** [comment]
OK, walk the file tree and do something like [this](http://stackoverflow.com/questions/17877296/checking-if-path-is-a-socket-in-python-2-7) and pass legitimate sockets to ignore.  If not, maybe consider not supporting skype until this problem can be fixed?

**Comment by lra** [comment]
Ignoring sockets seems legit, yes.
Anyone up for a PR?
I'll do one when I'll have time if not.

**Comment by lra** [comment]
Wait no we can't. If mackup links a folder that contains a socket file, it cannot excluded as the whole folder is linked.

I guess for this, we need a better Skype configuration. https://github.com/lra/mackup/blob/master/mackup/applications/skype.cfg is too broad

**Comment by spencergibb** [comment]
a folder with a socket is what caused this issue.

**Comment by lra** [comment]
Any Skype user can come up with a better config to sync?

**Comment by palexvs** [comment]
same issue. + i lost skype history after backuping :(
