### ISSUE TITLE
Immediate failure upon invocation (on OSX Mavericks 10, installed with homebrew)

### ISSUE THREAD

**Issue by yonkeltron** [lra/mackup#330]
After upgrading mackup to 0.7.4 via homebrew, it became impossible to use the executable as it immediately coughed and died.

The cough:

```
$ mackup
Traceback (most recent call last):
  File "/usr/local/bin/mackup", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2603, in <module>
    working_set.require(__requires__)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 666, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 565, in resolve
    raise DistributionNotFound(req)  # XXX put more info here
pkg_resources.DistributionNotFound: mackup==0.7.4
```

About my current setup:

```
$ uname -a
Darwin Concurrent-Chickpea.local 13.4.0 Darwin Kernel Version 13.4.0: Sun Aug 17 19:50:11 PDT 2014; root:xnu-2422.115.4~1/RELEASE_X86_64 x86_64

$ brew --version
0.9.5
```

If I can provide any additional info, please let me know.

Thanks!
- Jonathan

**Comment by EmilVarona** [comment]
fwiw, I had a similar issue. Homebrew installed v0.8.8 which gave me this error after installation

```
$ mackup backup
Traceback (most recent call last):
  File "/usr/local/Cellar/mackup/0.8.8/libexec/bin/mackup", line 9, in <module>
    load_entry_point('mackup==0.8.8', 'console_scripts', 'mackup')()
  File "/usr/local/Cellar/mackup/0.8.8/libexec/lib/python2.7/site-packages/mackup/main.py", line 52, in main
    if args['force']:
KeyError: 'force'
```

I uninstalled and reinstalled using pip, which installed v0.8.9.

**Comment by lra** [comment]
yep, homebrew is a little behind sometimes.
