### ISSUE TITLE
Something wrong with mackup in Yosemite 10.10

### ISSUE THREAD

**Issue by szhousun** [lra/mackup#340]
type command `mackup`, and then 

Traceback (most recent call last):
  File "/usr/local/bin/mackup", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2793, in <module>
    working_set.require(__requires__)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 673, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 576, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: mackup==0.7.4

**Comment by lra** [comment]
@szhousun @jbcdnr is it still a valid issue?

**Comment by jbcdnr** [comment]
I am sorry I cannot tell you if this is still an issue :/

**Comment by jarinudom** [comment]
I have not seen this issue in Yosemite retail.

**Comment by lra** [comment]
Ok feel free to reopen if it's still valid.
