### ISSUE TITLE
Traceback (most recent call last):   File "/usr/local/bin/mackup", line 9, in <module>     load_entry_point('mackup==0.7.4', 'console_scripts', 'mackup')()

### ISSUE THREAD

**Issue by hacpai** [lra/mackup#341]
OS is OSX 10.9.5

Shell is fish shell.

```
~ ❯ mackup backup
Mackup needs a directory to store your configuration files
Do you want to create it now ? </Users/MasterMac/Dropbox/Mackup> <Yes|No>Yes
Backing up Library/Preferences/com.jetbrains.PhpStorm.plist...
Backing up Library/Application Support/WebIde70...
Backing up Library/Preferences/WebIde70...
Backing up Library/Developer/Xcode/UserData/KeyBindings...
Backing up Library/Preferences/com.googlecode.iterm2.plist...
Backing up Library/Application Support/BetterTouchTool...
Backing up Library/Preferences/com.hegenberg.BetterTouchTool.plist...
Backing up .subversion...
Backing up Library/Application Support/Mou...
Backing up Library/Preferences/com.mouapp.Mou.LSSharedFileList.plist...
Backing up Library/Preferences/com.mouapp.Mou.plist...
Backing up .mpv/config...
Backing up Library/Preferences/com.panic.Transmit.plist...
Backing up Library/Application Support/Transmit/Metadata...
Backing up .ssh...
Backing up Library/Preferences/com.divisiblebyzero.Spectacle.plist...
Backing up Library/Preferences/org.vim.MacVim.LSSharedFileList.plist...
Backing up Library/Preferences/org.vim.MacVim.plist...
Backing up Library/Application Support/KeyRemap4MacBook/private.xml...
Backing up Library/Preferences/org.pqrs.KeyRemap4MacBook.plist...
Backing up Library/Application Support/Sublime Text 2/Pristine Packages...
Backing up Library/Application Support/Sublime Text 2/Installed Packages...
Backing up Library/Application Support/Sublime Text 2/Packages...
Backing up .hgignore_global...
Backing up Library/Preferences/org.herf.Flux.plist...
Backing up .config/fish/functions...
Backing up .config/fish/config.fish...
Backing up .config/fish/completions...
Backing up Library/Preferences/com.lightheadsw.Caffeine.plist...
Backing up Library/Preferences/com.alice.mac.go2shell.plist...
Backing up Library/Preferences/com.apple.iChat.AIM.plist...
Backing up Library/Preferences/com.apple.iChat.Jabber.plist...
Backing up Library/Preferences/com.apple.iChat.StatusMessages.plist...
Backing up Library/Preferences/com.apple.iChat.Yahoo.plist...
Backing up Library/Application Support/SuperDuper!...
Traceback (most recent call last):
  File "/usr/local/bin/mackup", line 9, in <module>
    load_entry_point('mackup==0.7.4', 'console_scripts', 'mackup')()
  File "/usr/local/lib/python2.7/site-packages/mackup/main.py", line 48, in main
    app.backup()
  File "/usr/local/lib/python2.7/site-packages/mackup/application.py", line 90, in backup
    utils.copy(filepath, mackup_filepath)
  File "/usr/local/lib/python2.7/site-packages/mackup/utils.py", line 91, in copy
    shutil.copytree(src, dst)
  File "/usr/local/Cellar/python/2.7.8_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 208, in copytree
    raise Error, errors
shutil.Error: [('/Users/MasterMac/Library/Application Support/SuperDuper!/Copy Scripts/Standard Scripts', '/Users/MasterMac/Dropbox/Mackup/Library/Application Support/SuperDuper!/Copy Scripts/Standard Scripts', "[Errno 2] No such file or directory: '/Users/MasterMac/Library/Application Support/SuperDuper!/Copy Scripts/Standard Scripts'"), ('/Users/MasterMac/Library/Application Support/SuperDuper!/Scheduled Copies/SDUtil', '/Users/MasterMac/Dropbox/Mackup/Library/Application Support/SuperDuper!/Scheduled Copies/SDUtil', "[Errno 2] No such file or directory: '/Users/MasterMac/Library/Application Support/SuperDuper!/Scheduled Copies/SDUtil'")]
```

**Comment by kevinlangleyjr** [comment]
Any updates here? I'm getting the same errors.

**Comment by arcticlion** [comment]
The bug remained unchanged.
-- 
Finch
Sent with Airmail

在 2015年1月2日 下午1:54:12, Kevin Langley Jr (notifications@github.com) 写到:

Any updates here? I'm getting the same errors.

**Comment by johntdyer** [comment]
Same problem here, osx 10.10

**Comment by lra** [comment]
Still an issue?

**Comment by imapirate** [comment]
It is for me. I need to add SuperDuper! from the list of applications to ignore to get rid of the error.
