### ISSUE TITLE
subversion permission denied

### ISSUE THREAD

**Issue by codeanpeace** [lra/mackup#355]
Both `mackup backup` and `mackup uninstall` are unable to fully execute. Anyone can help explain to me why running backup backs a few files up and then breaks and uninstall does not successfully move back files and breaks. Thanks!
output after running `mackup uninstall`
```
Moving .subversion back into your home...
chmod: /Users/harrison/.subversion/auth: Permission denied
chflags: /Users/harrison/.subversion/auth: Permission denied
Traceback (most recent call last):
  File "/usr/local/Cellar/mackup/0.7.4/libexec/bin/mackup", line 9, in <module>
    load_entry_point('mackup==0.7.4', 'console_scripts', 'mackup')()
  File "/usr/local/Cellar/mackup/0.7.4/lib/python2.7/site-packages/mackup/main.py", line 69, in main
    app.uninstall()
  File "/usr/local/Cellar/mackup/0.7.4/lib/python2.7/site-packages/mackup/application.py", line 180, in uninstall
    utils.delete(home_filepath)
  File "/usr/local/Cellar/mackup/0.7.4/lib/python2.7/site-packages/mackup/utils.py", line 55, in delete
    shutil.rmtree(filepath)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 239, in rmtree
    onerror(os.listdir, path, sys.exc_info())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 237, in rmtree
    names = os.listdir(path)
OSError: [Errno 13] Permission denied: '/Users/harrison/.subversion/auth'
```

**Comment by lra** [comment]
Apparently your system has permissions that prevent mackup to move your `/Users/harrison/.subversion` folder around.
