### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by xged** [lra/mackup#440]
Traceback (most recent call last):
  File "/usr/bin/mackup", line 9, in <module>
    load_entry_point('mackup==0.7.4', 'console_scripts', 'mackup')()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 474, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2260, in load
    ['__name__'])
  File "/usr/lib/python3.4/site-packages/mackup/main.py", line 92
    print output
               ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by light94** [comment]
Hello!
After browsing the source code for Mackup, i've found that it was written in python2.x . Your system seems to have a default installation of python3 where print is a ***function*** , so you are getting this error. You can use python's 2to3 tool to solve this problem . Just run ***$ 2to3 -w main.py*** and it will be adapted to python3

**Comment by xged** [comment]
Correct. In **Manjaro**, the default `/usr/bin/python` is linked to `python3`.

**Comment by lra** [comment]
Can you try with 0.8? I merged some python3 compat changes.

**Comment by xged** [comment]
0.8 works fine!
