### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by boetter** [lra/mackup#460]
Any idea why this might be happening to me?

![Screenshot] (https://dl.dropboxusercontent.com/u/4260/Screen%20Shot%202015-02-07%20at%2013.59.26.png)

**Comment by lra** [comment]
Mackup does not seem to be able to move `.shsh/.cache/lib-osx.jar`
Frankly, I think the app config is bad, as Mackup should not try to sync cache files, and `.shsh/.cache` is an obvious name.

@stechico you added support for this https://github.com/lra/mackup/blob/master/mackup/applications/shsh-blobs.cfg, any idea?

**Comment by nickolson** [comment]
I'm getting the exact same error just it occurs when I try to backup my oh-my-zsh config file. Is there any way to modify the oh-my-zsh app config to ignore the .git directory?
![screen shot 2015-08-24 at 8 40 28 pm](https://cloud.githubusercontent.com/assets/3261021/9456037/6af7206a-4aa0-11e5-9ff4-669155d77f6f.png)

**Comment by lra** [comment]
No: https://github.com/lra/mackup/issues/602

**Comment by jwmann** [comment]
I'm getting the exact same error and Traceback as @boetter

**Comment by boetter** [comment]
I just upgraded through Homebrew and seems the bug is still the same.

<img width="843" alt="screen shot 2015-09-16 at 22 31 40" src="https://cloud.githubusercontent.com/assets/1336222/9917598/c7764a44-5cc2-11e5-8ea2-7e4ca83daa13.png">

**Comment by skywinder** [comment]
Same with me. just installed and got this error:

    OSError: [Errno 13] Permission denied: '/Users/petrkorolev/.shsh/.cache/lib-osx.jar'

**Comment by jwmann** [comment]
2 years later and still have this issue.

**Comment by nicofirst1** [comment]
I'm having the exact same problem on Ubuntu 18.04
```
Restoring .oh-my-zsh/custom ...
You already have a folder named .oh-my-zsh/custom in your home.
Do you want to replace it with your backup ? <Yes|No>yes
Traceback (most recent call last):
  File "/home/dizzi/.conda/envs/mcup/bin/mackup", line 8, in <module>
    sys.exit(main())
  File "/home/dizzi/.conda/envs/mcup/lib/python3.7/site-packages/mackup/main.py", line 120, in main
    app.restore()
  File "/home/dizzi/.conda/envs/mcup/lib/python3.7/site-packages/mackup/application.py", line 201, in restore
    utils.delete(home_filepath)
  File "/home/dizzi/.conda/envs/mcup/lib/python3.7/site-packages/mackup/utils.py", line 68, in delete
    shutil.rmtree(filepath)
  File "/home/dizzi/.conda/envs/mcup/lib/python3.7/shutil.py", line 498, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/home/dizzi/.conda/envs/mcup/lib/python3.7/shutil.py", line 496, in rmtree
    os.rmdir(path)
PermissionError: [Errno 13] Permission denied: '/home/dizzi/.oh-my-zsh/custom'
```

**Comment by lra** [comment]
ok, unless someone has a fix, the only thing I can do is remove support for oh-my-zsh and shsh.

**Comment by MR-T77** [comment]
I've got a similar message for a different app: 
`PermissionError: [Errno 13] Permission denied: '/Users/asapinto/.config/filezilla'`

**Comment by alexanderadam** [comment]
And I'm getting this issues for `DefaultKeyBinding.dict`:

```
$ mackup backup

Mackup needs a directory to store your configuration files
Do you want to create it now? </Users/username/Library/Mobile Documents/com~apple~CloudDocs/Mackup> <Yes|No>Yes
Backing up .ansible ...
Backing up Library/Preferences/com.apple.Music.eq.plist ...
Backing up Library/Preferences/com.apple.Music.plist ...
Backing up .asdfrc ...
Backing up .bashrc ...
Backing up .bash_profile ...
Backing up .profile ...
Backing up .bundle/config ...
Backing up Library/KeyBindings/DefaultKeyBinding.dict ...
Traceback (most recent call last):
  File "/usr/local/bin/mackup", line 33, in <module>
    sys.exit(load_entry_point('mackup==0.8.32', 'console_scripts', 'mackup')())
  File "/usr/local/Cellar/mackup/0.8.32/libexec/lib/python3.9/site-packages/mackup/main.py", line 93, in main
    app.backup()
  File "/usr/local/Cellar/mackup/0.8.32/libexec/lib/python3.9/site-packages/mackup/application.py", line 119, in backup
    utils.delete(home_filepath)
  File "/usr/local/Cellar/mackup/0.8.32/libexec/lib/python3.9/site-packages/mackup/utils.py", line 66, in delete
    os.remove(filepath)
PermissionError: [Errno 13] Permission denied: '/Users/username/Library/KeyBindings/DefaultKeyBinding.dict'
```
