### ISSUE TITLE
Mackup deletes all files

### ISSUE THREAD

**Issue by nigulh** [lra/mackup#467]
I tried the following configuration
[storage]
engine = file_system
path =
directory = .mackup

$ mackup backup
Backing up /Users/nigulh/.profile ...
Backing up /Users/nigulh/.mackup ...
Traceback (most recent call last):
  File "/usr/local/Cellar/mackup/0.8.3/libexec/bin/mackup", line 9, in <module>
    load_entry_point('mackup==0.8.3', 'console_scripts', 'mackup')()
  File "/usr/local/Cellar/mackup/0.8.3/libexec/lib/python2.7/site-packages/mackup/main.py", line 46, in main
    app.backup()
  File "/usr/local/Cellar/mackup/0.8.3/libexec/lib/python2.7/site-packages/mackup/application.py", line 96, in backup
    utils.link(mackup_filepath, filepath)
  File "/usr/local/Cellar/mackup/0.8.3/libexec/lib/python2.7/site-packages/mackup/utils.py", line 127, in link
    assert os.path.exists(target)
AssertionError

Fortunately I have a backup of the files at ~/GoogleDrive/Mackup.
What is the easiest way to restore the files from this backup?

**Comment by Timidger** [comment]
Have you tried to run `mackup uninstall`? That should copy the files back to their original destination. Though, if I were you I'd copy that folder so if it messes up you can always do it manually.

**Comment by ckng** [comment]
Using a working existing configuration
```
[storage]
engine = file_system
path = Dropbox
directory = mackup

[applications_to_sync]
git
mackup
ssh
vscode
zsh
```

When doing `$mackup back`, ran into the AssertionError and it deleted all files backup in the Dropbox folder. All symlinks become stale. 
```
Traceback (most recent call last):
  File "/home/ckng/.local/bin/mackup", line 8, in <module>
    sys.exit(main())
  File "/home/ckng/.local/lib/python3.10/site-packages/mackup/main.py", line 130, in main
    app.copy_files_to_mackup_folder()
  File "/home/ckng/.local/lib/python3.10/site-packages/mackup/application.py", line 102, in copy_files_to_mackup_folder
    utils.copy(home_filepath, mackup_filepath)
  File "/home/ckng/.local/lib/python3.10/site-packages/mackup/utils.py", line 95, in copy
    assert os.path.exists(src)
AssertionError
```

**Comment by lra** [comment]
I guess this is an edge case where you try to run `mackup backup` after you've run `mackup link install`.
In this case mackup tries to backup links pointing to files that are in the backup folder, which leads to mackup trying to remove those files 1st to make space for the links you want to backup.
This should not be allowed, but I'd like you to confirm this is the case before digging and making a test for it.

**Comment by ckng** [comment]
Yes, this is a critial data loss bug. I've added some new custom files to the list of backup, with existing backup files already symlinked. Doing `mackup back` deleted all the backup'ed files. I may also answered yes somewhere in the process. Dry run didn't throw error.
So a check should be in place if it is already symlinked, it should not try to "backup" leading to data loss.
