### ISSUE TITLE
Mackup not working with fish configs in a user specified dir

### ISSUE THREAD

**Issue by musophob** [lra/mackup#491]
In the process of setting up a new machine. Was "macking up" just fine until I set up fish shell along with some files in `~/.config` for fish (`~/.config` is under mackup's control). For some reason mackup is choking on replacing files inside `~/.config/fish`.

Here are my custom mackup settings. Did not make a `.mackup.cfg` and haven't messed with anything else as far as mackup is concerned.

    [sean@hesap]-(~/D/M/.mackup)
    └> ls
    other_dotfiles.cfg

    ┌[sean@hesap]-(~/D/M/.mackup)
    └> cat other_dotfiles.cfg
    [application]
    name = Other confs
    
    [configuration_files]
    .bin
    .bro
    .config
    .cheat
    .gitignore_global
    .hushlogin

# Sample output of the failures:

## 1 - `backup`

_My fish configs:_

    ┌[sean@hesap]-(~/D/Mackup)
    └> ls -la .config/fish/
    total 96
    drwx------@ 7   238 Mar 16 19:23 ./
    drwx------@ 8   272 Mar 16 15:33 ../
    -rw-r--r--@ 1  6148 Mar 16 17:26 .DS_Store
    -rw-r--r--@ 1   625 Mar 16 17:24 config.fish
    -rw-r--r--@ 1 30650 Mar 16 19:24 fish_history
    -rw-------@ 1   976 Mar 16 19:24 fishd.c82a14449b39
    drwxr-xr-x@ 5   170 Mar 16 19:19 functions/

_Then run a mackup_

    ┌[sean@hesap]-(~/D/Mackup)
    └> mackup backup
    Backing up /Users/sean/Library/Preferences/com.googlecode.iterm2.plist ...
    A file named /Users/sean/Dropbox/Mackup/Library/Preferences/com.googlecode.iterm2.plist already exists in the backup.
    Are you sure that you want to replace it ? <Yes|No>Yes
    Backing up /Users/sean/Library/Application Support/Sublime Text 3/Packages/User ...
    A folder named /Users/sean/Dropbox/Mackup/Library/Application Support/Sublime Text 3/Packages/User already exists in the backup.
    Are you sure that you want to replace it ? <Yes|No>Yes
    Backing up /Users/sean/.tmux.conf ...
    A file named /Users/sean/Dropbox/Mackup/.tmux.conf already exists in the backup.
    Are you sure that you want to replace it ? <Yes|No>Yes
    Backing up /Users/sean/Library/Preferences/com.divisiblebyzero.Spectacle.plist ...
    A file named /Users/sean/Dropbox/Mackup/Library/Preferences/com.divisiblebyzero.Spectacle.plist already exists in the backup.
    Are you sure that you want to replace it ? <Yes|No>Yes
    Backing up /Users/sean/Library/Preferences/org.herf.Flux.plist ...
    A file named /Users/sean/Dropbox/Mackup/Library/Preferences/org.herf.Flux.plist already exists in the backup.
    Are you sure that you want to replace it ? <Yes|No>Yes
    Backing up /Users/sean/.config/fish/functions ...
    A folder named /Users/sean/Dropbox/Mackup/.config/fish/functions already exists in the backup.
    Are you sure that you want to replace it ? <Yes|No>Yes
    Traceback (most recent call last):
      File "/usr/local/Cellar/mackup/0.8.3/libexec/bin/mackup", line 9, in <module>
        load_entry_point('mackup==0.8.3', 'console_scripts', 'mackup')()
      File "/usr/local/Cellar/mackup/0.8.3/libexec/lib/python2.7/site-packages/mackup/main.py", line 46, in main
        app.backup()
      File "/usr/local/Cellar/mackup/0.8.3/libexec/lib/python2.7/site-packages/mackup/application.py", line 85, in backup
        utils.copy(filepath, mackup_filepath)
      File "/usr/local/Cellar/mackup/0.8.3/libexec/lib/python2.7/site-packages/mackup/utils.py", line 84, in copy
        assert os.path.exists(src)
    AssertionError

_and the `.config/fish/functions` dir is awol._

    ┌[sean@hesap]-(~/D/Mackup)
    └> ls -la .config/fish/
    total 96
    drwx------@ 6   204 Mar 16 19:24 ./
    drwx------@ 8   272 Mar 16 15:33 ../
    -rw-r--r--@ 1  6148 Mar 16 17:26 .DS_Store
    -rw-r--r--@ 1   625 Mar 16 17:24 config.fish
    -rw-r--r--@ 1 30769 Mar 16 19:24 fish_history
    -rw-------@ 1   976 Mar 16 19:24 fishd.c82a14449b39

Luckily I did the Dropbox deleted files maneuver and didn't loose an hour of tinkering.

## 2 - `uninstall`

Tried uninstalling to start over, but it doesn't work.

    ┌[sean@hesap]-(~)
    └> mackup uninstall
    You are going to uninstall Mackup.
    Every configuration file, setting and dotfile managed by Mackup will be unlinked and moved back to their original place, in your home folder.
    Are you sure ? <Yes|No>Yes
    Reverting /Users/sean/Library/Preferences/com.googlecode.iterm2.plist ...
    Reverting /Users/sean/Library/Application Support/Sublime Text 3/Packages/User ...
    Reverting /Users/sean/.tmux.conf ...
    Reverting /Users/sean/Library/Preferences/com.divisiblebyzero.Spectacle.plist ...
    Reverting /Users/sean/Library/Preferences/org.herf.Flux.plist ...
    Reverting /Users/sean/.config/fish/config.fish ...
    Traceback (most recent call last):
      File "/usr/local/Cellar/mackup/0.8.3/libexec/bin/mackup", line 9, in <module>
        load_entry_point('mackup==0.8.3', 'console_scripts', 'mackup')()
      File "/usr/local/Cellar/mackup/0.8.3/libexec/lib/python2.7/site-packages/mackup/main.py", line 88, in main
        app.uninstall()
      File "/usr/local/Cellar/mackup/0.8.3/libexec/lib/python2.7/site-packages/mackup/application.py", line 185, in uninstall
        utils.copy(mackup_filepath, home_filepath)
      File "/usr/local/Cellar/mackup/0.8.3/libexec/lib/python2.7/site-packages/mackup/utils.py", line 84, in copy
        assert os.path.exists(src)
    AssertionError

_The uninstall fails, linked files are still `$HOME`._

    ┌[sean@hesap]-(~)
    └> lla | grep '>'
    rwxr-xr-x     40B .bash_profile@ -> /Users/sean/Dropbox/Mackup/.bash_profile
    rwxr-xr-x     34B .bashrc@ -> /Users/sean/Dropbox/Mackup/.bashrc
    rwxr-xr-x     31B .bin@ -> /Users/sean/Dropbox/Mackup/.bin
    rwxr-xr-x     31B .bro@ -> /Users/sean/Dropbox/Mackup/.bro
    rwxr-xr-x     33B .cheat@ -> /Users/sean/Dropbox/Mackup/.cheat
    rwxr-xr-x     34B .config@ -> /Users/sean/Dropbox/Mackup/.config
    rwxr-xr-x     33B .gemrc@ -> /Users/sean/Dropbox/Mackup/.gemrc
    rwxr-xr-x     37B .gitconfig@ -> /Users/sean/Dropbox/Mackup/.gitconfig
    rwxr-xr-x     44B .gitignore_global@ -> /Users/sean/Dropbox/Mackup/.gitignore_global
    rwxr-xr-x     37B .hushlogin@ -> /Users/sean/Dropbox/Mackup/.hushlogin
    rwxr-xr-x     34B .mackup@ -> /Users/sean/Dropbox/Mackup/.mackup
    rwxr-xr-x     33B .pryrc@ -> /Users/sean/Dropbox/Mackup/.pryrc
    rwxr-xr-x     31B .ssh@ -> /Users/sean/Dropbox/Mackup/.ssh
    rwxr-xr-x     40B .subversion@ -> /Users/sean/Downloads/Mackup/.subversion
    rwxr-xr-x     33B .vimrc@ -> /Users/sean/Dropbox/Mackup/.vimrc
    rwxr-xr-x     34B .zlogin@ -> /Users/sean/Dropbox/Mackup/.zlogin
    rwxr-xr-x     35B .zlogout@ -> /Users/sean/Dropbox/Mackup/.zlogout
    rwxr-xr-x     37B .zpreztorc@ -> /Users/sean/Dropbox/Mackup/.zpreztorc
    rwxr-xr-x     36B .zprofile@ -> /Users/sean/Dropbox/Mackup/.zprofile
    rwxr-xr-x     34B .zshenv@ -> /Users/sean/Dropbox/Mackup/.zshenv
    rwxr-xr-x     33B .zshrc@ -> /Users/sean/Dropbox/Mackup/.zshrc

## 3 - Manual overide

I deleted `.config` from the mackup directory, removed the link in home directory, pasted `.config` back into `~` from another location, and ran `mackup backup` again. No luck.

_With fresh, non-linked `.config`_

    ┌[sean@hesap]-(~)
    └> la
    .
    [...]
    ├── .cheat -> /Users/sean/Dropbox/Mackup/.cheat
    ├── .config
    ├── .dropbox
    [...]

_Mackup throws the error_

    ┌[sean@hesap]-(~)
    └> mackup backup
    Backing up /Users/sean/.config ...
    Traceback (most recent call last):
      File "/usr/local/Cellar/mackup/0.8.3/libexec/bin/mackup", line 9, in <module>
        load_entry_point('mackup==0.8.3', 'console_scripts', 'mackup')()
      File "/usr/local/Cellar/mackup/0.8.3/libexec/lib/python2.7/site-packages/mackup/main.py", line 46, in main
        app.backup()
      File "/usr/local/Cellar/mackup/0.8.3/libexec/lib/python2.7/site-packages/mackup/application.py", line 92, in backup
        utils.copy(filepath, mackup_filepath)
      File "/usr/local/Cellar/mackup/0.8.3/libexec/lib/python2.7/site-packages/mackup/utils.py", line 99, in copy
        shutil.copytree(src, dst)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 208, in copytree
        raise Error, errors
    shutil.Error: [('/Users/sean/.config/fish/config.fish', '/Users/sean/Dropbox/Mackup/.config/fish/config.fish', "[Errno 2] No such file or directory: '/Users/sean/.config/fish/config.fish'"), ('/Users/sean/.config/fish/functions', '/Users/sean/Dropbox/Mackup/.config/fish/functions', "[Errno 2] No such file or directory: '/Users/sean/.config/fish/functions'")]

_And `.config` still exists, not linked to the mackup dir._

    [sean@hesap]-(~)
    └> la 
    .
    ...
    ├── .cheat -> /Users/sean/Dropbox/Mackup/.cheat
    ├── .config
    ├── .dropbox
    [...]

<hr>

Failures are repeatable from `bash` and `zsh`, so I don't think it's anything to do with fish shell itself, just the custom configs I added.

Any ideas? I've become quite attached to macking up and don't want to loose it now, after all the good times we've shared.

**Comment by musophob** [comment]
Solved my own issue, sort of. I didn't realize that mackup already has configs for backing up `~/.config/fish` and `~/.config/oh-my-fish`, so my custom rule for the whole `~/.config` was mucking things up.
