### ISSUE TITLE
No such file or directory: ~/Dropbox/Mackup/.hgrc 

### ISSUE THREAD

**Issue by aristidesfl** [lra/mackup#559]
I get this message when I try to restore on a new machine:

```
$ mackup restore
Traceback (most recent call last):
  File "/usr/local/Cellar/mackup/0.8.5/libexec/bin/mackup", line 9, in <module>
    load_entry_point('mackup==0.8.5', 'console_scripts', 'mackup')()
  File "/usr/local/Cellar/mackup/0.8.5/libexec/lib/python2.7/site-packages/mackup/main.py", line 74, in main
    app.restore()
  File "/usr/local/Cellar/mackup/0.8.5/libexec/lib/python2.7/site-packages/mackup/application.py", line 125, in restore
    home_filepath))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py", line 162, in samefile
    s1 = os.stat(f1)
OSError: [Errno 2] No such file or directory: '/Users/user/Dropbox/Mackup/.hgrc'

```

Facts:

1. I did not back up mercurial
2. Mercurial is **not** on my list of applications to backup
3. Therefore there is no .hgrc on my Dropbox
4. The new machine where I did restore, didn't have a .mackup config file, so it had to figure out which applications to restore
5. Backing up .mackup solves this problem because it won't try to restore mercurial

Questions:

1. How does mackup decide which files to restore when there is no black/white list?
2. Is Mackup checking which files already exist on the machine to decide which files to restore?
3. If so, shouldn't it instead check which files exist on the backup?

**Comment by joeyhoer** [comment]
I'm seeing this exact same issue.

On a machine that already has applications installed, but where mackup has not yet run. I get the `No such file or directory` error for the  applications that are not in the back up (or are only installed on the "new" machine).

@aristidesfl, I agree that mackup should check to see if the files exist in the backup before trying to restore them.

**Comment by kfinlay** [comment]
EThe
Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=6.1.51&pv=8.3]
On Sat, Jun 13, 2015 at 10:53, Joey Hoer <notifications@github.com> wrote:
I'm seeing this exact same issue.

On a machine that already has applications installed, but where mackup has not
yet run. I get the No such file or directory error for the applications that are not in the back up (or are only installed
on the "new" machine).

@aristidesfl [https://github.com/aristidesfl] , I agree that mackup should check to see if the files exist in the backup
before trying to restore them.

—
Reply to this email directly or view it on GitHub
[https://github.com/lra/mackup/issues/559#issuecomment-111723912] .[https://github.com/notifications/beacon/AE-2h2L2iC_JtaiP3MNExwV4YnuKvBFcks5oTEmXgaJpZM4E1Opn.gif]

**Comment by reitermarkus** [comment]
This happened to me too. Then I tried deleting my unused preferences in Dropbox, but forgot that I had the (now broken) symlinks in my `Library`.

I cleaned out all broken symlinks with this (use at your own risk):

    find -L ~/Library -type l | sed -e 's/\ /\\\ /' | xargs rm -f

After this, `mackup restore` went through without any error.

Of course, this is only a temporary solution.

**Comment by joeyhoer** [comment]
Good catch.

You may be right. I think `mackup` was run on the machine I was referencing earlier, and then the backup was overwritten, so there may have been broken symlinks. Which kinda makes more sense as to why this is breaking.

Your command works beautifully. To explain why it works (for future readers), the script searches the current user's `Library` directory for all symlinks (`-type l`), but before it does that, it traverses all symbolic links (`-L`). According to the find manual, "If the referenced file does not exist, the file information and type will be for the link itself." So it only returns the broken links. The rest of the command escapes spaces in filenames and then removes the files, though, that part may be unnecessary. The following command should accomplish the same thing:

    find -L ~/Library -type l -delete

**Comment by reitermarkus** [comment]
I tried the `-delete` flag, but it said this isn't supported for symlinks. At least not on OS X.

**Comment by joeyhoer** [comment]
You're right. I've amended the explanation above.
