### ISSUE TITLE
CopyQ Clipboard Manager

### ISSUE THREAD

**Issue by orschiro** [lra/mackup#659]
I would like to create a config for [CopyQ](https://github.com/hluk/CopyQ).

However, it creates random file names for some of its config files. Example:

```
copyq_tab_JmNsaXBib2FyZA==.dat
```

How can we capture this? 

Thankfully,

Robert

**Comment by lra** [comment]
Just sync the folder that contains those files.
See https://github.com/lra/mackup/tree/master/doc#add-support-for-an-application-or-any-file-or-directory

**Comment by hgs81** [comment]
Backing up copyq configuration occurs following error:
```
Backing up .config/copyq ...
Traceback (most recent call last):
  File "/usr/local/Cellar/mackup/0.8.18/libexec/bin/mackup", line 9, in <module>
    load_entry_point('mackup==0.8.18', 'console_scripts', 'mackup')()
  File "/usr/local/Cellar/mackup/0.8.18/libexec/lib/python2.7/site-packages/mackup/main.py", line 90, in main
    app.backup()
  File "/usr/local/Cellar/mackup/0.8.18/libexec/lib/python2.7/site-packages/mackup/application.py", line 114, in backup
    utils.copy(home_filepath, mackup_filepath)
  File "/usr/local/Cellar/mackup/0.8.18/libexec/lib/python2.7/site-packages/mackup/utils.py", line 105, in copy
    shutil.copytree(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 208, in copytree
    raise Error, errors
```
How to disable specific apps from being backed up?

**Comment by lra** [comment]
See [Don't sync an application](https://github.com/lra/mackup/tree/master/doc#dont-sync-an-application).

**Comment by lyveng** [comment]
syncing copyq is failing because the file `$HOME/.config/copy/.copyq_s` is a socket file which cannot be copied normally.

Also weirdly `cp -rf` successfully copies the file. But I don't think there is any point in backing up the socket file.

```
➜  ~ mackup backup
Backing up .config/copyq ...
A folder named /home/livingstone.se/Dropbox/Mackup/.config/copyq already exists in the backup.
Are you sure that you want to replace it ? <Yes|No>Yes
Traceback (most recent call last):
  File "/home/livingstone.se/.local/bin/mackup", line 11, in <module>
    load_entry_point('mackup==0.8.26', 'console_scripts', 'mackup')()
  File "/home/livingstone.se/.local/lib/python3.7/site-packages/mackup/main.py", line 91, in main
    app.backup()
  File "/home/livingstone.se/.local/lib/python3.7/site-packages/mackup/application.py", line 107, in backup
    utils.copy(home_filepath, mackup_filepath)
  File "/home/livingstone.se/.local/lib/python3.7/site-packages/mackup/utils.py", line 102, in copy
    shutil.copytree(src, dst)
  File "/usr/lib/python3.7/shutil.py", line 365, in copytree
    raise Error(errors)
shutil.Error: [('/home/livingstone.se/.config/copyq/.copyq_s', '/home/livingstone.se/Dropbox/Mackup/.config/copyq/.copyq_s', "[Errno 6] No such device or address: '/home/livingstone.se/.config/copyq/.copyq_s'")]
➜  ~ ls -l .config/copyq/.copyq_s 
srwxr-xr-x 1 livingstone.se livingstone.se 0 Aug 15 04:09 .config/copyq/.copyq_s
```

A workaround would be to stop copyq and then do the backup since the socket file is created when copyq is started and deleted when copyq is stopped.

I've created hluk/CopyQ#1196 to check if the copyq team can move the socket file ~/.config/copyq/.copyq_s to /tmp directory.
