### ISSUE TITLE
Issues installing with Brew 0.9.5

### ISSUE THREAD

**Issue by nocode99** [lra/mackup#667]
On OS X 10.10.5 with Brew 0.9.5

I installed mackup with no issues and tried running 'mackup backup' and got this error:

Traceback (most recent call last):
  File "/usr/local/Cellar/mackup/0.8.8/libexec/bin/mackup", line 9, in <module>
    load_entry_point('mackup==0.8.8', 'console_scripts', 'mackup')()
  File "/usr/local/Cellar/mackup/0.8.8/libexec/lib/python2.7/site-packages/mackup/main.py", line 52, in main
    if args['force']:
KeyError: 'force'

I was able to uninstall and then install with Pip instead and was able to backup with no issues.

**Comment by DannyNemer** [comment]
I am have the same issue, which occurs for both `mackup backup` and `mackup restore`:
```shell
Traceback (most recent call last):
  File "/usr/local/Cellar/mackup/0.8.12/libexec/bin/mackup", line 9, in <module>
    load_entry_point('mackup==0.8.12', 'console_scripts', 'mackup')()
  File "/usr/local/Cellar/mackup/0.8.12/libexec/lib/python2.7/site-packages/mackup/main.py", line 121, in main
    app.restore()
  File "/usr/local/Cellar/mackup/0.8.12/libexec/lib/python2.7/site-packages/mackup/application.py", line 188, in restore
    utils.link(mackup_filepath, home_filepath)
  File "/usr/local/Cellar/mackup/0.8.12/libexec/lib/python2.7/site-packages/mackup/utils.py", line 133, in link
    assert os.path.exists(target)
AssertionError
```
