### ISSUE TITLE
Restore Error

### ISSUE THREAD

**Issue by Anzumana** [lra/mackup#710]
Traceback (most recent call last):
      File "/usr/local/Cellar/mackup/0.8.12/libexec/bin/mackup", line 9, in <module>
        load_entry_point('mackup==0.8.12', 'console_scripts', 'mackup')()
      File "/usr/local/Cellar/mackup/0.8.12/libexec/lib/python2.7/site-packages/mackup/main.py", line 121, in main
        app.restore()
      File "/usr/local/Cellar/mackup/0.8.12/libexec/lib/python2.7/site-packages/mackup/application.py", line 157, in restore
    home_filepath))
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py", line 156, in samefile
        s2 = os.stat(f2)
    OSError: [Errno 2] No such file or directory:     '/Users/anzumana/Library/Preferences/com.googlecode.iterm2.plist'

Systeminformation:
iMac 10.10.5
Python 2.7.5
zsh

Not sure how i can debug to figure this one out.
Any help greatly appreciated.
Love the app btw :)

**Comment by Hout** [comment]
Here is another one:
```
$ mackup restore
Traceback (most recent call last):
  File "/usr/local/Cellar/mackup/0.8.12/libexec/bin/mackup", line 9, in <module>
    load_entry_point('mackup==0.8.12', 'console_scripts', 'mackup')()
  File "/usr/local/Cellar/mackup/0.8.12/libexec/lib/python2.7/site-packages/mackup/main.py", line 121, in main
    app.restore()
  File "/usr/local/Cellar/mackup/0.8.12/libexec/lib/python2.7/site-packages/mackup/application.py", line 157, in restore
    home_filepath))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py", line 156, in samefile
    s2 = os.stat(f2)
OSError: [Errno 2] No such file or directory: '/Users/jeroen/Library/Preferences/com.adobe.Photoshop.plist'
```
Python 2.7.10
OSX 10.11.4 beta
bash

**Comment by Hout** [comment]
This happened after I changed my user name. There are still old symbolic links that point to the previous home directory that does not exist anymore.

**Comment by Hout** [comment]
It would be a nice to have if mackup would remove links in the restore process IF the target does not exist anymore.

**Comment by glaszig** [comment]
> It would be a nice to have if mackup would remove links in the restore process IF the target does not exist anymore.

this would not be good. let's say you have fish and fisherman backed up with mackup. fisherman puts links into fish's config directory.
on a new machine you then run `mackup restore` and because of the way mackup handles `.mackup.cfg` entries, it might try to restore fish with its symlinks first -- essentially restoring orphaned links -- and then it restores fisherman and its files, making the symlinks valid again.
