### ISSUE TITLE
Problem with .ssh/config

### ISSUE THREAD

**Issue by welly** [lra/mackup#711]
Having a problem with backing up my .ssh directory. I'm getting this error when I run mackup backup:

Backing up .ssh/config ...
A file named /Users/alastair/ownCloud/mackup/.ssh/config already exists in the backup.
Are you sure that you want to replace it ? <Yes|No>yes
Traceback (most recent call last):
  File "/usr/local/Cellar/mackup/0.8.12/libexec/bin/mackup", line 9, in <module>
    load_entry_point('mackup==0.8.12', 'console_scripts', 'mackup')()
  File "/usr/local/Cellar/mackup/0.8.12/libexec/lib/python2.7/site-packages/mackup/main.py", line 90, in main
    app.backup()
  File "/usr/local/Cellar/mackup/0.8.12/libexec/lib/python2.7/site-packages/mackup/application.py", line 106, in backup
    utils.copy(home_filepath, mackup_filepath)
  File "/usr/local/Cellar/mackup/0.8.12/libexec/lib/python2.7/site-packages/mackup/utils.py", line 90, in copy
    assert os.path.exists(src)
AssertionError

And then the config file is deleted. All other files (*.keys, authorized_keys etc.) are fine and untouched, it's just the config file.

Ideas?

**Comment by florentb** [comment]
same here

**Comment by raypatterson** [comment]
Also having this issue. For me, it seems to want to back up my `~/.ssh/config` file whether I configure it to back up the parent directory or not.

**Comment by rogeriopradoj** [comment]
# Kinda solved this problem with mackup and ssh config backup / restore:

1) Reverted old backup of `.ssh` folder:
```
rm -rf ~/.ssh
mv ~/Dropbox/Mackup/.ssh ~/.ssh
```

2) Created `~/.mackup.cfg` file and `~/.mackup` folder
```
touch ~/.mackup.cfg && mkdir ~/.mackup
```

3) Downloaded two examples configs from [docs](https://github.com/lra/mackup/tree/d0c26e6/doc/.mackup) into `~/.mackup` folder
```
cd ~/.mackup
wget https://raw.githubusercontent.com/lra/mackup/d0c26e605bf224c2b9194b88f9f777f8b00ac8e6/doc/.mackup/mackup.cfg
wget https://raw.githubusercontent.com/lra/mackup/d0c26e605bf224c2b9194b88f9f777f8b00ac8e6/doc/.mackup/ssh.cfg
```

4) Run `mackup backup`
```
mackup backup

# Backing up .ssh ...
# Backing up .mackup ...
# Backing up .mackup.cfg ...
```

--

Please test with your environment!
