### ISSUE TITLE
Byobu - trying to backup a socket for SSH agent gives error message

### ISSUE THREAD

**Issue by neil-greenwood** [lra/mackup#758]
If your Byobu configuration contains a socket connected to the local SSH agent, you get an error message when running `mackup backup`:

```
Backing up .byobu ...
Traceback (most recent call last):
  File "/usr/local/Cellar/mackup/0.8.12/libexec/bin/mackup", line 9, in <module>
    load_entry_point('mackup==0.8.12', 'console_scripts', 'mackup')()
  File "/usr/local/Cellar/mackup/0.8.12/libexec/lib/python2.7/site-packages/mackup/main.py", line 90, in main
    app.backup()
  File "/usr/local/Cellar/mackup/0.8.12/libexec/lib/python2.7/site-packages/mackup/application.py", line 113, in backup
    utils.copy(home_filepath, mackup_filepath)
  File "/usr/local/Cellar/mackup/0.8.12/libexec/lib/python2.7/site-packages/mackup/utils.py", line 105, in copy
    shutil.copytree(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 208, in copytree
    raise Error, errors
shutil.Error: [('/Users/neil/.byobu/.ssh-agent', '/Users/neil/./Mackup/.byobu/.ssh-agent', "[Errno 102] Operation not supported on socket: '/Users/neil/.byobu/.ssh-agent'")]
```

**Comment by lra** [comment]
should be fixed by https://github.com/lra/mackup/pull/759
