### ISSUE TITLE
ConfigParser.NoSectionError: No section: 'application'

### ISSUE THREAD

**Issue by iainbeeston** [lra/mackup#776]
I'm having a bit of trouble with mackup, I've installed mackup from home brew and everything has been running ok for a while. But now I've started getting an error:
```
Traceback (most recent call last):
  File "/usr/local/Cellar/mackup/0.8.12/libexec/bin/mackup", line 9, in <module>
    load_entry_point('mackup==0.8.12', 'console_scripts', 'mackup')()
  File "/usr/local/Cellar/mackup/0.8.12/libexec/lib/python2.7/site-packages/mackup/main.py", line 65, in main
    app_db = ApplicationsDatabase()
  File "/usr/local/Cellar/mackup/0.8.12/libexec/lib/python2.7/site-packages/mackup/appsdb.py", line 44, in __init__
    app_pretty_name = config.get('application', 'name')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'application'
```

This happens with every mackup command, so I can't do anything with mackup. I've tried removing my .mackup.cfg file (I had assumed it wasn't parsing correctly) but that hasn't helped.

I'm using mackup 0.8.12 with python 2.7.11 on mac os 10.11.3.

Any help would be appreciated, I'll debug what I can.

**Comment by philippbosch** [comment]
Ran into the same issue, and for me the problem was that I had created a custom application file in `~/.mackup` which didn't have the required `[application]` section in it.
