### ISSUE TITLE
KeyError: 'insurgency'

### ISSUE THREAD

**Issue by drgeb** [lra/mackup#780]
I observe the following

> mackup backup

Mackup needs a directory to store your configuration files
Do you want to create it now ? </Users/drgeb/Documents/Mackup> <Yes|No>Yes
Backing up .mackup ...
Backing up .mackup.cfg ...
Traceback (most recent call last):
  File "/usr/local/Cellar/mackup/0.8.12/libexec/bin/mackup", line 9, in <module>
    load_entry_point('mackup==0.8.12', 'console_scripts', 'mackup')()
  File "/usr/local/Cellar/mackup/0.8.12/libexec/lib/python2.7/site-packages/mackup/main.py", line 86, in main
    app_db.get_files(app_name),
  File "/usr/local/Cellar/mackup/0.8.12/libexec/lib/python2.7/site-packages/mackup/appsdb.py", line 145, in get_files
    return self.apps[name]['configuration_files']
KeyError: 'insurgency'

Not sure how to fix this

**Comment by IvanIFChen** [comment]
`insurgency` is not supported, you can see a list of supported applications from `mackup list`.
