### ISSUE TITLE
New update gives error with Skype

### ISSUE THREAD

**Issue by nuno-agostinho** [lra/mackup#791]
I noticed that Skype's preferences aren't synced as of the new update. That's all right but since I had previously backed up Skype, it gave me the following error:

```
Backing up Library/Application Support/Skype/shared_dynco ...
A folder named /Users/Daniel/Dropbox/Mackup/Library/Application Support/Skype/shared_dynco already exists in the backup.
Are you sure that you want to replace it ? <Yes|No>Yes
Traceback (most recent call last):
  File "/usr/local/Cellar/mackup/0.8.13/libexec/bin/mackup", line 9, in <module>
    load_entry_point('mackup==0.8.13', 'console_scripts', 'mackup')()
  File "/usr/local/Cellar/mackup/0.8.13/libexec/lib/python2.7/site-packages/mackup/main.py", line 90, in main
    app.backup()
  File "/usr/local/Cellar/mackup/0.8.13/libexec/lib/python2.7/site-packages/mackup/application.py", line 106, in backup
    utils.copy(home_filepath, mackup_filepath)
  File "/usr/local/Cellar/mackup/0.8.13/libexec/lib/python2.7/site-packages/mackup/utils.py", line 90, in copy
    assert os.path.exists(src)
AssertionError
```

This is easily solvable by removing the Skype folder. Therefore, Mackup should either remove the folder and warn the user that Skype is no longer synced or simply ask the user to remove it themselves.

**Comment by walterheck** [comment]
Hitting this as well. Can it be fixed by any chance?

**Comment by lra** [comment]
Skype support removed in 0.8.14
