### ISSUE TITLE
[Errno 6] No such device or address

### ISSUE THREAD

**Issue by orschiro** [lra/mackup#883]
Dear all, 

Can anyone please advise me how to handle the following error?

Thankfully,

-Robert

```
orschiro@x230:~$ mackup backup
Backing up .config/copyq ...
A folder named /home/orschiro/Dropbox/Mackup/.config/copyq already exists in the backup.
Are you sure that you want to replace it ? <Yes|No>Yes
Traceback (most recent call last):
  File "/usr/local/bin/mackup", line 9, in <module>
    load_entry_point('mackup==0.8.14', 'console_scripts', 'mackup')()
  File "/usr/local/lib/python2.7/dist-packages/mackup/main.py", line 90, in main
    app.backup()
  File "/usr/local/lib/python2.7/dist-packages/mackup/application.py", line 106, in backup
    utils.copy(home_filepath, mackup_filepath)
  File "/usr/local/lib/python2.7/dist-packages/mackup/utils.py", line 105, in copy
    shutil.copytree(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 208, in copytree
    raise Error, errors
shutil.Error: [('/home/orschiro/.config/copyq/.copyq_s', '/home/orschiro/Dropbox/Mackup/.config/copyq/.copyq_s', "[Errno 6] No such device or address: '/home/orschiro/.config/copyq/.copyq_s'"), ('/home/orschiro/.config/copyq/.copyq_m', '/home/orschiro/Dropbox/Mackup/.config/copyq/.copyq_m', "[Errno 6] No such device or address: '/home/orschiro/.config/copyq/.copyq_m'")]
```

**Comment by edwardmp** [comment]
I'm seeing the same issue, but only regarding Heroku stuff:
```
Backing up .heroku/plugins ...
A folder named /Users/Edward/Dropbox/Mackup/.heroku/plugins already exists in the backup.
Are you sure that you want to replace it ? <Yes|No>Yes
Traceback (most recent call last):
  File "/opt/boxen/homebrew/Cellar/mackup/0.8.14/libexec/bin/mackup", line 9, in <module>
    load_entry_point('mackup==0.8.14', 'console_scripts', 'mackup')()
  File "/opt/boxen/homebrew/Cellar/mackup/0.8.14/libexec/lib/python2.7/site-packages/mackup/main.py", line 90, in main
    app.backup()
  File "/opt/boxen/homebrew/Cellar/mackup/0.8.14/libexec/lib/python2.7/site-packages/mackup/application.py", line 106, in backup
    utils.copy(home_filepath, mackup_filepath)
  File "/opt/boxen/homebrew/Cellar/mackup/0.8.14/libexec/lib/python2.7/site-packages/mackup/utils.py", line 105, in copy
    shutil.copytree(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 208, in copytree
    raise Error, errors
shutil.Error: [('/Users/Edward/.heroku/plugins/heroku-config/.git/description', '/Users/Edward/Dropbox/Mackup/.heroku/plugins/heroku-config/.git/description', "[Errno 2] No such file or directory: '/Users/Edward/.heroku/plugins/heroku-config/.git/description'"), ('/Users/Edward/.heroku/plugins/heroku-config/.git/hooks/applypatch-msg.sample', '/Users/Edward/Dropbox/Mackup/.heroku/plugins/heroku-config/.git/hooks/applypatch-msg.sample', "[Errno 2] No such file or directory: '/Users/Edward/.heroku/plugins/heroku-config/.git/hooks/applypatch-msg.sample'"), ('/Users/Edward/.heroku/plugins/heroku-config/.git/hooks/commit-msg.sample', '/Users/Edward/Dropbox/Mackup/.heroku/plugins/heroku-config/.git/hooks/commit-msg.sample', "[Errno 2] No such file or directory: '/Users/Edward/.heroku/plugins/heroku-config/.git/hooks/commit-msg.sample'"), ('/Users/Edward/.heroku/plugins/heroku-config/.git/hooks/post-update.sample', '/Users/Edward/Dropbox/Mackup/.heroku/plugins/heroku-config/.git/hooks/post-update.sample', "[Errno 2] No such file or directory: '/Users/Edward/.heroku/plugins/heroku-config/.git/hooks/post-update.sample'"), ('/Users/Edward/.heroku/plugins/heroku-config/.git/hooks/pre-applypatch.sample', '/Users/Edward/Dropbox/Mackup/.heroku/plugins/heroku-config/.git/hooks/pre-applypatch.sample', "[Errno 2] No such file or directory: '/Users/Edward/.heroku/plugins/heroku-config/.git/hooks/pre-applypatch.sample'"), ('/Users/Edward/.heroku/plugins/heroku-config/.git/hooks/pre-commit.sample', '/Users/Edward/Dropbox/Mackup/.heroku/plugins/heroku-config/.git/hooks/pre-commit.sample', "[Errno 2] No such file or directory: '/Users/Edward/.heroku/plugins/heroku-config/.git/hooks/pre-commit.sample'"), ('/Users/Edward/.heroku/plugins/heroku-config/.git/hooks/pre-push.sample', '/Users/Edward/Dropbox/Mackup/.heroku/plugins/heroku-config/.git/hooks/pre-push.sample', "[Errno 2] No such file or directory: '/Users/Edward/.heroku/plugins/heroku-config/.git/hooks/pre-push.sample'"), ('/Users/Edward/.heroku/plugins/heroku-config/.git/hooks/pre-rebase.sample', '/Users/Edward/Dropbox/Mackup/.heroku/plugins/heroku-config/.git/hooks/pre-rebase.sample', "[Errno 2] No such file or directory: '/Users/Edward/.heroku/plugins/heroku-config/.git/hooks/pre-rebase.sample'"), ('/Users/Edward/.heroku/plugins/heroku-config/.git/hooks/prepare-commit-msg.sample', '/Users/Edward/Dropbox/Mackup/.heroku/plugins/heroku-config/.git/hooks/prepare-commit-msg.sample', "[Errno 2] No such file or directory: '/Users/Edward/.heroku/plugins/heroku-config/.git/hooks/prepare-commit-msg.sample'"), ('/Users/Edward/.heroku/plugins/heroku-config/.git/hooks/update.sample', '/Users/Edward/Dropbox/Mackup/.heroku/plugins/heroku-config/.git/hooks/update.sample', "[Errno 2] No such file or directory: '/Users/Edward/.heroku/plugins/heroku-config/.git/hooks/update.sample'"), ('/Users/Edward/.heroku/plugins/heroku-config/.git/info/exclude', '/Users/Edward/Dropbox/Mackup/.heroku/plugins/heroku-config/.git/info/exclude', "[Errno 2] No such file or directory: '/Users/Edward/.heroku/plugins/heroku-config/.git/info/exclude'")]

```

**Comment by edwardmp** [comment]
OK I think I know why it happens.

For *some* reason certain stuff related to the .git folder was symlinked to files belonging to GitHub's mac app. I have no clue why this has happened in the first page, but removing those symlinks (that point to a file that no longer exists) solves the issue. You can do this manually but in some cases you can just delete the whole local git repo and clone it again to put the proper files in the .git folder back in place.
Once I did this the problem was solved.

Example .git folder where the issue occurred:
```
drwxr-xr-x+  14 Edward  staff   476B 20 sep 01:26 .
drwxr-xr-x+  15 Edward  staff   510B  2 sep 16:59 ..
-rw-r--r--+   1 Edward  staff   103B  2 sep 16:59 FETCH_HEAD
-rw-r--r--+   1 Edward  staff    23B  2 sep 16:59 HEAD
-rw-r--r--+   1 Edward  staff    41B  2 sep 16:59 ORIG_HEAD
-rw-r--r--+   1 Edward  staff   316B 13 nov  2013 config
lrwxr-xr-x    1 Edward  staff    84B 13 nov  2013 description -> /Applications/GitHub.app/Contents/Resources/git/share/git-core/templates/description (**no longer exists**)
drwxr-xr-x+  11 Edward  staff   374B 13 nov  2013 hooks
-rw-r--r--+   1 Edward  staff    60K 20 sep 01:25 index
drwxr-xr-x+   3 Edward  staff   102B 13 nov  2013 info
drwxr-xr-x+   4 Edward  staff   136B 13 nov  2013 logs
drwxr-xr-x+ 245 Edward  staff   8,1K  1 aug 17:34 objects
-rw-r--r--+   1 Edward  staff   255B 13 nov  2013 packed-refs
drwxr-xr-x+   5 Edward  staff   170B 13 nov  2013 refs
```

**Comment by orschiro** [comment]
Thanks @edwardmp!

Where can I find the local `git` folder?

- In the Mackup backup folder
- or in my original config folder?

Thankfully,

-Robert

**Comment by orschiro** [comment]
However, my application problem does not have a `git` folder.

![image](https://cloud.githubusercontent.com/assets/170947/18699659/f8b1ad0e-7fd2-11e6-81ac-163ed2881837.png)

![image](https://cloud.githubusercontent.com/assets/170947/18699666/023ae728-7fd3-11e6-83bf-2bb72c16f2ef.png)

**Comment by edwardmp** [comment]
@orschiro 
No it's not Git specific. That was just an example. Check if the problematic file is symlinked to another file that does not exist.

**Comment by orschiro** [comment]
Thanks!

Problem solved for now by deleting the files that Mackup complained about.

Warmly,

-Robert

![image](https://cloud.githubusercontent.com/assets/170947/18813460/bd9dcfe2-82fa-11e6-86d6-7fba9217a878.png)
