### ISSUE TITLE
Problem right after installation

### ISSUE THREAD

**Issue by delahaya** [lra/mackup#940]
I do have Dropbox installed on my machine and after install mackup with brew, when running `mackup backup` I receive this error...
`Traceback (most recent call last):
  File "/usr/local/Cellar/mackup/0.8.15/libexec/bin/mackup", line 9, in <module>
    load_entry_point('mackup==0.8.15', 'console_scripts', 'mackup')()
  File "/usr/local/Cellar/mackup/0.8.15/libexec/lib/python2.7/site-packages/mackup/main.py", line 65, in main
    app_db = ApplicationsDatabase()
  File "/usr/local/Cellar/mackup/0.8.15/libexec/lib/python2.7/site-packages/mackup/appsdb.py", line 34, in __init__
    if config.read(config_file):
  File "/Library/Python/2.7/site-packages/backports/configparser/__init__.py", line 705, in read
    self._read(fp, filename)
  File "/Library/Python/2.7/site-packages/backports/configparser/__init__.py", line 1109, in _read
    optname = self.optionxform(optname.rstrip())
UnicodeEncodeError: 'ascii' codec can't encode character u'\xdc' in position 28: ordinal not in range(128)`

Not sure what I'm doing wrong but I'm almost positive this issue is the end-user(me).

Thank you,
Christian

**Comment by MadeOfMagicAndWires** [comment]
Reinstall mackup using python version 3 instead of 2

**Comment by bronze** [comment]
got the same errors, osx, installed python3 via homebrew but osx keeps using python2
any tips?

**Comment by craigmdennis** [comment]
Looks like a duplicate of https://github.com/lra/mackup/issues/667

**Comment by tryer3000** [comment]
I got another problem right after install mackup.
Environment:
python3 on ubuntu 16.04

```
Traceback (most recent call last):
  File "/home/joshua/.local/bin/mackup", line 11, in <module>
    sys.exit(main())
  File "/home/joshua/.local/lib/python3.5/site-packages/mackup/main.py", line 64, in main
    mckp = Mackup()
  File "/home/joshua/.local/lib/python3.5/site-packages/mackup/mackup.py", line 24, in __init__
    self._config = config.Config()
  File "/home/joshua/.local/lib/python3.5/site-packages/mackup/config.py", line 52, in __init__
    self._path = self._parse_path()
  File "/home/joshua/.local/lib/python3.5/site-packages/mackup/config.py", line 225, in _parse_path
    path = path.decode("utf-8")
AttributeError: 'str' object has no attribute 'decode'
```

**Comment by luzzbob** [comment]
delete the /usr/local/Cellar/mackup/0.8.16/libexec/lib/python2.7/site-packages/mackup/applications/ubersicht.cfg (modify apropriately) because it's the one causing problems
