### ISSUE TITLE
"mackup list" reports UnicodeEncodeError under linux

### ISSUE THREAD

**Issue by EMayej** [lra/mackup#961]
redhat 7.2
python 2.7.13 (installed with linuxbrew)
mackup 0.8.5

ERROR:
```shell
> mackup list
Traceback (most recent call last):
  File "/home/emayej/.linuxbrew/Cellar/mackup/0.8.15/libexec/bin/mackup", line 9, in <module>
    load_entry_point('mackup==0.8.15', 'console_scripts', 'mackup')()
  File "/home/emayej/.linuxbrew/Cellar/mackup/0.8.15/libexec/lib/python2.7/site-packages/mackup/main.py", line 65, in main
    app_db = ApplicationsDatabase()
  File "/home/emayej/.linuxbrew/Cellar/mackup/0.8.15/libexec/lib/python2.7/site-packages/mackup/appsdb.py", line 34, in __init__
    if config.read(config_file):
  File "/home/emayej/.linuxbrew/lib/python2.7/site-packages/backports/configparser/__init__.py", line 705, in read
    self._read(fp, filename)
  File "/home/emayej/.linuxbrew/lib/python2.7/site-packages/backports/configparser/__init__.py", line 1109, in _read
    optname = self.optionxform(optname.rstrip())
UnicodeEncodeError: 'ascii' codec can't encode character u'\xdc' in position 28: ordinal not in range(128)
```

This configuration file triggers the error:
https://github.com/lra/mackup/blame/master/mackup/applications/ubersicht.cfg#L5
especially this character:
**Ü**

@kfinlay

**Comment by kfinlay** [comment]
Sorry, I only ever tested this with Python 3. @lra, what's the right way to fix the encoding? Is there a way to do it in the config, is this in the parser?

Also, it appears that Ubersicht might have a new default widgets directory ~/Library/Application Support/tracesOf.Uebersicht. Replacing the current directory with this in the config would fix the problem, but potentially break someone's older setup.

**Comment by erch** [comment]
I have also the issue with Python 3 on a linux machine.

The error occurs because the configuration file applications/ubersicht.cfg contains a Ü and my host is configured to use UTF-8.

As a quick fix I changed File "/home/emayej/.linuxbrew/Cellar/mackup/0.8.15/libexec/lib/python2.7/site-packages/mackup/appsdb.py", line 34 by adding the encoding parameter set to utf-8:

if config.read(config_file,"utf_8")

This should work for most of the host configuration  because UTF-8 encompass Ascii. Didn't dig too much into the issue and how it is handled with python 2.

Eric

**Comment by MadeOfMagicAndWires** [comment]
@kfinlay The right way is #909. There are already 3 PR's out for this bug (and about as many issues)
