### ISSUE TITLE
Renaming home directory leaves Mackup in an unrecoverable state

### ISSUE THREAD

**Issue by borland502** [lra/mackup#964]
Renaming the home directory though the [standard means](https://support.apple.com/en-us/HT201548) leaves no way to "reset" mackup for restore.  After fixing the dropbox app, mackup will panic at the first symlink

```bash
Restoring .ssh/authorized_keys ...
Traceback (most recent call last):
  File "/usr/local/Cellar/mackup/0.8.15/libexec/bin/mackup", line 9, in <module>
    load_entry_point('mackup==0.8.15', 'console_scripts', 'mackup')()
  File "/usr/local/Cellar/mackup/0.8.15/libexec/lib/python2.7/site-packages/mackup/main.py", line 121, in main
    app.restore()
  File "/usr/local/Cellar/mackup/0.8.15/libexec/lib/python2.7/site-packages/mackup/application.py", line 158, in restore
    home_filepath))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py", line 156, in samefile
    s2 = os.stat(f2)
OSError: [Errno 2] No such file or directory: '/Users/foo/Library/Application Support/Sublime Text 2/Packages/User'
```
Deleting all the symlinks manually lets mackup proceed at what it does best.  It's a huge edge case, but I figure I'd mention the circumstance.  Thanks for the utility.

**Comment by paxperscientiam** [comment]
Maybe a `mackup refresh` or `mackup reset` is in order.
