### ISSUE TITLE
friendlier errors when running into permissions trouble

### ISSUE THREAD

**Issue by olets** [lra/mackup#978]
My first try at `mackup backup` ran intro trouble with [qlImageSize](https://github.com/Nyx0uf/qlImageSize), which by default is owned by `root`.

```bash
Backing up Library/Quicklook ...
Traceback (most recent call last):
  File "/usr/local/Cellar/mackup/0.8.16/libexec/bin/mackup", line 9, in <module>
    load_entry_point('mackup==0.8.16', 'console_scripts', 'mackup')()
  File "/usr/local/Cellar/mackup/0.8.16/libexec/lib/python2.7/site-packages/mackup/main.py", line 90, in main
    app.backup()
  File "/usr/local/Cellar/mackup/0.8.16/libexec/lib/python2.7/site-packages/mackup/application.py", line 116, in backup
    utils.delete(home_filepath)
  File "/usr/local/Cellar/mackup/0.8.16/libexec/lib/python2.7/site-packages/mackup/utils.py", line 68, in delete
    shutil.rmtree(filepath)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 250, in rmtree
    os.remove(fullname)
OSError: [Errno 13] Permission denied: '/Users/[user]/Library/Quicklook/qlImageSize.qlgenerator/Contents/Info.plist'
```

Running `chown -R user /Users/[user]/Library/Quicklook/qlImageSize.qlgenerator` got it looking like the other QuickLook plugins, and after `mackup uninstall` my next `mackup backup` worked.

It'd be great to have a more meaningful error — it's easy to imagine someone getting stumped.

**Comment by ParadiseDS** [comment]
Same Question here, almost destroyed my quicklook plugins as mackup messed up  plugins' permission, and some scripts in it (such as qlcolorcode) cannot be correctly executed, quite annoying.

I don't know if the permissions of some other things have been left incorrect as the process was interrupt.

I also have the qlImageSize installed, and its default owner is root:staff
