### ISSUE TITLE
Error when backing up Sketch

### ISSUE THREAD

**Issue by JannesV** [lra/mackup#981]
Just tried to backup everthing and it gave the following error. Running the latest version.

```
Backing up Library/Application Support/com.bohemiancoding.sketch3 ...
Traceback (most recent call last):
  File "/usr/local/Cellar/mackup/0.8.16/libexec/bin/mackup", line 9, in <module>
    load_entry_point('mackup==0.8.16', 'console_scripts', 'mackup')()
  File "/usr/local/Cellar/mackup/0.8.16/libexec/lib/python2.7/site-packages/mackup/main.py", line 90, in main
    app.backup()
  File "/usr/local/Cellar/mackup/0.8.16/libexec/lib/python2.7/site-packages/mackup/application.py", line 114, in backup
    utils.copy(home_filepath, mackup_filepath)
  File "/usr/local/Cellar/mackup/0.8.16/libexec/lib/python2.7/site-packages/mackup/utils.py", line 105, in copy
    shutil.copytree(src, dst)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 208, in copytree
    raise Error, errors
shutil.Error: [('/Users/jannesmac/Library/Application Support/com.bohemiancoding.sketch3/Plugins/SubtlePatterns.sketchplugin/Contents/Sketch/SubtlePatterns.framework/Modules', '/Users/jannesmac/Dropbox/Mackup/Library/Application Support/com.bohemiancoding.sketch3/Plugins/SubtlePatterns.sketchplugin/Contents/Sketch/SubtlePatterns.framework/Modules', "[Errno 2] No such file or directory: '/Users/jannesmac/Library/Application Support/com.bohemiancoding.sketch3/Plugins/SubtlePatterns.sketchplugin/Contents/Sketch/SubtlePatterns.framework/Modules'")]
```
![Image](http://i.imgur.com/6mph8ub.png)

**Comment by gianpaj** [comment]
Still an issue

```
$ mackup --version
Mackup 0.8.27
```

Sketch Version 62 (91390)

```
Backing up Library/Application Support/com.bohemiancoding.sketch3 ...
Traceback (most recent call last):
  File "/usr/local/bin/mackup", line 11, in <module>
    load_entry_point('mackup==0.8.27', 'console_scripts', 'mackup')()
  File "/usr/local/Cellar/mackup/0.8.27_1/libexec/lib/python3.8/site-packages/mackup/main.py", line 88, in main
    app.backup()
  File "/usr/local/Cellar/mackup/0.8.27_1/libexec/lib/python3.8/site-packages/mackup/application.py", line 117, in backup
    utils.copy(home_filepath, mackup_filepath)
  File "/usr/local/Cellar/mackup/0.8.27_1/libexec/lib/python3.8/site-packages/mackup/utils.py", line 102, in copy
    shutil.copytree(src, dst)
  File "/usr/local/Cellar/mackup/0.8.27_1/libexec/lib/python3.8/shutil.py", line 548, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/usr/local/Cellar/mackup/0.8.27_1/libexec/lib/python3.8/shutil.py", line 504, in _copytree
    raise Error(errors)
shutil.Error: [('/Users/gpalumbo/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Abstract.sketchplugin/Contents/Sketch/ObjectiveGit.framework/Versions/A/Headers/GTObjectDatabase.h', '/Users/gpalumbo/Dropbox/Mackup/Library/Application Support/com.bohemiancoding.sketch3/Plugins/Abstract.sketchplugin/Contents/Sketch/ObjectiveGit.framework/Versions/A/Headers/GTObjectDatabase.h', "[Errno 2] No such file or directory:
...
```

**Comment by lra** [comment]
Looks like their config folder includes files that can't be copied, weird.

If this is an issue for everyone using Sketch, I'd rather remove the support for it.

@enkia you've added support for it in https://github.com/lra/mackup/pull/811, did it ever work for you?

**Comment by enkia** [comment]
It worked at the time that I added it but they've since changed where they store preferences. I also stopped syncing preferences for Sketch since, while it did work, I kept having to register license each time I switched macs.

**Comment by lra** [comment]
Sounds like nobody's really using it then. OK to remove support for it?

**Comment by enkia** [comment]
Yep, I’m personally fine with removing it.
